// Beer Runner — catalogue des 362 bières + traductions anglaises
const BIERES_CULTES = [
  { nom: "Petit Orval", emoji: "🐟", type: "Trappiste de table", origine: "Belgique — abbaye d'Orval", force: "4,5%", fa: "Le petit Orval, servi uniquement à l'auberge de l'abbaye : les moines le réservent aux pèlerins de passage." },
  { nom: "Westvleteren 12", emoji: "⛪", type: "Trappiste quadrupel", origine: "Belgique — Westvleteren", force: "10,2%", fa: "Brassée par des moines sans étiquette : pour l'acheter, rendez-vous à l'abbaye." },
  { nom: "Westvleteren Blond", emoji: "⛪", type: "Trappiste blonde", origine: "Belgique — Westvleteren", force: "5,8%", fa: "La petite des moines, en vente uniquement à la porte du monastère." },
  { nom: "Westvleteren 8", emoji: "⛪", type: "Trappiste brune", origine: "Belgique — Westvleteren", force: "8%", fa: "Une des trois Westvleteren, aussi rare que ses soeurs." },
  { nom: "Orval", emoji: "🐟", type: "Trappiste unique", origine: "Belgique — abbaye d'Orval", force: "6,2%", fa: "Une truite aurait rendu un anneau perdu à la fontaine de l'abbaye : elle est sur l'étiquette." },
  { nom: "Rochefort 6", emoji: "🔢", type: "Trappiste dubbel", origine: "Belgique — Rochefort", force: "7,5%", fa: "La plus discrète des trois Rochefort, favorite des connaisseurs." },
  { nom: "Rochefort 8", emoji: "🔢", type: "Trappiste dubbel", origine: "Belgique — Rochefort", force: "9,2%", fa: "L'équilibre parfait entre la 6 et la 10, disent les moines." },
  { nom: "Rochefort 10", emoji: "🔢", type: "Trappiste quadrupel", origine: "Belgique — Rochefort", force: "11,3%", fa: "Les chiffres viennent des densités d'avant-guerre. La 10 se sirote comme un whisky." },
  { nom: "Rochefort Triple Extra", emoji: "🔢", type: "Trappiste triple", origine: "Belgique — Rochefort", force: "8,7%", fa: "Édition limitée des moines : quand elle est là, on se jette dessus." },
  { nom: "Chimay Bleue", emoji: "⛪", type: "Trappiste strong ale", origine: "Belgique — Scourmont", force: "9%", fa: "La Grande Réserve : corsée, épicée, taillée pour vieillir en cave." },
  { nom: "Chimay Rouge", emoji: "⛪", type: "Trappiste dubbel", origine: "Belgique — Scourmont", force: "7%", fa: "La première Chimay de l'histoire, douce et fruitée." },
  { nom: "Chimay Blanche", emoji: "⛪", type: "Trappiste triple", origine: "Belgique — Scourmont", force: "8%", fa: "La « Cinq Cents » : amertume nette, muscat en finale." },
  { nom: "Chimay Dorée", emoji: "⛪", type: "Trappiste blonde", origine: "Belgique — Scourmont", force: "4,8%", fa: "Pendant des décennies, elle était réservée aux moines et à leurs invités." },
  { nom: "Westmalle Tripel", emoji: "⛪", type: "Trappiste triple", origine: "Belgique — Westmalle", force: "9,5%", fa: "LA triple de référence : le monde entier essaie de la copier." },
  { nom: "Westmalle Dubbel", emoji: "⛪", type: "Trappiste dubbel", origine: "Belgique — Westmalle", force: "7%", fa: "La dubbel mère : elle a fixé le style des brunes d'abbaye." },
  { nom: "Westmalle Extra", emoji: "⛪", type: "Trappiste blonde", origine: "Belgique — Westmalle", force: "4,8%", fa: "La bière de table des moines eux-mêmes, introuvable en magasin." },
  { nom: "Achel Blond", emoji: "⛪", type: "Trappiste blonde", origine: "Belgique — Hamont-Achel", force: "8%", fa: "Brassée à la frontière néerlandaise dans la plus discrète des abbayes trappistes." },
  { nom: "Achel Bruin", emoji: "⛪", type: "Trappiste brune", origine: "Belgique — Hamont-Achel", force: "8,5%", fa: "Brune de garde, avec un léger goût de caramel grillé." },
  { nom: "Leffe Blonde", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Dinant", force: "6,6%", fa: "Née à l'abbaye de Leffe en 1152 : les moines brassaient pour financer l'entretien." },
  { nom: "Leffe Brune", emoji: "🇧🇪", type: "Abbaye brune", origine: "Belgique — Dinant", force: "6,5%", fa: "Douce et torréfiée, la brune du dimanche après-midi." },
  { nom: "Leffe Rituel 9°", emoji: "🇧🇪", type: "Abbaye forte", origine: "Belgique — Dinant", force: "9%", fa: "Une Leffe qui monte : à siroter lentement, pas à gorgées." },
  { nom: "Grimbergen Blonde", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Grimbergen", force: "6%", fa: "Le phénix sur l'étiquette : l'abbaye a brûlé et rebâti plein de fois." },
  { nom: "Grimbergen Optimo Bruno", emoji: "🇧🇪", type: "Abbaye forte", origine: "Belgique — Grimbergen", force: "10%", fa: "La « bière des érudits » de Grimbergen, tonneau d'excellence." },
  { nom: "Maredsous 8", emoji: "🇧🇪", type: "Abbaye dubbel", origine: "Belgique — Maredsous", force: "8%", fa: "Brune de l'abbaye bénédictine, parfaite avec un fromage du même nom." },
  { nom: "Maredsous 10", emoji: "🇧🇪", type: "Abbaye quadrupel", origine: "Belgique — Maredsous", force: "10%", fa: "La corpsé de la famille, à partager à deux… ou pas." },
  { nom: "St Bernardus Abt 12", emoji: "🇧🇪", type: "Abbaye quadrupel", origine: "Belgique — Watou", force: "10%", fa: "Brassée jadis pour les moines de Westvleteren : la cousine laïque de la 12." },
  { nom: "St Bernardus Wit", emoji: "🇧🇪", type: "Blanche d'abbaye", origine: "Belgique — Watou", force: "5,5%", fa: "Blanche crémeuse d'inspiration traditionnelle, citron facultatif." },
  { nom: "St Bernardus Christmas Ale", emoji: "🇧🇪", type: "Abbaye de Noël", origine: "Belgique — Watou", force: "10%", fa: "La bière de l'Avent flamand : épices, dattes, et un bon feu de cheminée." },
  { nom: "St Bernardus Grottenbier", emoji: "🇧🇪", type: "Abbaye brune", origine: "Belgique — Watou", force: "6,5%", fa: "Conçue pour vieillir dans les grottes de marbre de la région." },
  { nom: "Affligem Blonde", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Affligem", force: "6,8%", fa: "Bière d'abbaye millénaire : la mousse est digne d'un cappuccino." },
  { nom: "Affligem Tripel", emoji: "🇧🇪", type: "Abbaye triple", origine: "Belgique — Affligem", force: "9,5%", fa: "Triple de haut vol, héritée des moines d'Affligem." },
  { nom: "Val-Dieu Triple", emoji: "🇧🇪", type: "Abbaye triple", origine: "Belgique — Aubel", force: "9%", fa: "L'abbaye du Val-Dieu a rouvert sa brasserie en l'an 2000." },
  { nom: "Val-Dieu Brune", emoji: "🇧🇪", type: "Abbaye brune", origine: "Belgique — Aubel", force: "8%", fa: "Brune de garde brassée avec l'eau de la source de l'abbaye." },
  { nom: "Tongerlo Tripel", emoji: "🇧🇪", type: "Abbaye triple", origine: "Belgique — Tongerlo", force: "8%", fa: "Une triple de la plus ancienne abbaye de chanoines du pays." },
  { nom: "Floreffe Blonde", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Floreffe", force: "6,3%", fa: "Les chanoines de Floreffe brassaient déjà au XIIe siècle." },
  { nom: "Postel Blond", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Postel", force: "7%", fa: "Le goût rond des moines de la forêt de Postel." },
  { nom: "Bornem Double", emoji: "🇧🇪", type: "Abbaye dubbel", origine: "Belgique — Bornem", force: "6,5%", fa: "Brune de l'abbaye de Bornem, dans le style des anciennes bières de jeûne." },
  { nom: "Ename Dubbel", emoji: "🇧🇪", type: "Abbaye dubbel", origine: "Belgique — Ename", force: "7%", fa: "Une brune de l'abbaye disparue d'Ename, ressuscitée par brasserie." },
  { nom: "Saint-Feuillien Brune", emoji: "🇧🇪", type: "Abbaye brune", origine: "Belgique — Le Roeulx", force: "8,5%", fa: "L'abbaye de Saint-Feuillien brasse depuis 1873 en pays de Hainaut." },
  { nom: "Steenbrugge Dubbel", emoji: "🇧🇪", type: "Abbaye dubbel", origine: "Belgique — Bruges", force: "6,5%", fa: "Brune de l'abbaye Saint-Pierre de Steenbrugge, recette des moines." },
  { nom: "Duvel", emoji: "😈", type: "Strong pale ale", origine: "Belgique — Puurs", force: "8,5%", fa: "Un brasseur a goûté le premier essai : « c'est un vrai Duvel ! » — un vrai démon." },
  { nom: "Duvel Tripel Hop", emoji: "😈", type: "Strong pale ale", origine: "Belgique — Puurs", force: "9,5%", fa: "Trois houblons frais au lieu d'un : la version pentathlon du Démon." },
  { nom: "Chouffe", emoji: "🧙", type: "Strong golden ale", origine: "Belgique — Achouffe", force: "8%", fa: "Le gnome à barbe blanche protège la brasserie… et pique des bières aux touristes." },
  { nom: "La Chouffe Mc Chouffe", emoji: "🧌", type: "Scotch ale belge", origine: "Belgique — Achouffe", force: "8%", fa: "Une scotch brassée par des Belges avec un nain écossais sur l'étiquette." },
  { nom: "N'Ice Chouffe", emoji: "🇧🇪", type: "Bière de Noël", origine: "Belgique — Achouffe", force: "10%", fa: "La Chouffe d'hiver : épices et quetsches, le bonnet du gnome en plus." },
  { nom: "Delirium Tremens", emoji: "🇧🇪", type: "Strong pale ale", origine: "Belgique — Melle", force: "8,5%", fa: "L'éléphant rose sur la bouteille : ici, le délire est dans le nom." },
  { nom: "Delirium Noël", emoji: "🇧🇪", type: "Bière de Noël", origine: "Belgique — Melle", force: "8%", fa: "La version de fête du délire : à consommer avant de voir des rennes roses." },
  { nom: "Piraat", emoji: "🏴‍☠️", type: "Strong pale ale", origine: "Belgique — Wuustwezel", force: "10,5%", fa: "10,5% de houblon corsé : le pavillon noir des bières belges." },
  { nom: "Gulden Draak", emoji: "🐉", type: "Strong dark ale", origine: "Belgique — Ertvelde", force: "10,5%", fa: "Le dragon doré : une triple fermentation en bouteille, un monstre de garde." },
  { nom: "Kasteel Rouge", emoji: "🇧🇪", type: "Bière cerise-guimauve", origine: "Belgique — Ingelmunster", force: "8%", fa: "Brune macérée aux cerises : le dessert qui se boit." },
  { nom: "Kasteel Donker", emoji: "🇧🇪", type: "Strong dark ale", origine: "Belgique — Ingelmunster", force: "11%", fa: "La brune du château d'Ingelmunster, douce comme un sirop d'orge." },
  { nom: "Ciney Blonde", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Ciney", force: "7%", fa: "La blonde de Ciney, à la mousse généreuse et à l'amertume polie." },
  { nom: "Ciney Brune", emoji: "🇧🇪", type: "Strong brune", origine: "Belgique — Ciney", force: "7,5%", fa: "La brune du Condroz, crème de caramel et d'orge." },
  { nom: "Brigand", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Oostkamp", force: "9%", fa: "Nommée d'après les rebelles de 1798 : elle mène sa propre révolte." },
  { nom: "Lucifer", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Verhaeghe", force: "8%", fa: "Le nom dit tout : dorée, diablement épicée, damnation garantie." },
  { nom: "Judas", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Alken", force: "8,5%", fa: "Un baiser et une gifle : douceur d'abord, alcool ensuite." },
  { nom: "Gouden Carolus Classic", emoji: "🇧🇪", type: "Strong dark ale", origine: "Belgique — Mechelen", force: "8,5%", fa: "La bière de l'empereur Charles Quint, disent les brasseurs de Malines." },
  { nom: "Gouden Carolus Hopsinjoor", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Mechelen", force: "8,5%", fa: "Neuf houblons différents : la couronne se porte aussi sur la langue." },
  { nom: "Bush Ambrée", emoji: "🇧🇪", type: "Strong amber ale", origine: "Belgique — Péruwelz", force: "12%", fa: "La plus forte des bières belges classiques : à respecter, pas à defier." },
  { nom: "Barbar", emoji: "🍯", type: "Bière au miel", origine: "Belgique — Quenast", force: "8%", fa: "Une blonde au miel d'acacia : l'abeille fait la moitié du travail." },
  { nom: "Verboden Vrucht", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Wieze", force: "8,8%", fa: "Le fruit défendu : Adam et Ève sur l'étiquette, le péché dans le verre." },
  { nom: "Cuvée des Trolls", emoji: "🇧🇪", type: "Strong golden ale", origine: "Belgique — Dottignies", force: "7%", fa: "Brassée avec des oranges séchées : la bouche pleine et la tête légère." },
  { nom: "Satan Gold", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Igoulême", force: "8%", fa: "Une « bière des Dieux » : le marketing était déjà fort en 1988." },
  { nom: "Tripel Karmeliet", emoji: "🍺", type: "Triple aux trois céréales", origine: "Belgique — Buggenhout", force: "7,8%", fa: "Orge, froment ET avoine : la triple aux trois céréales, un délice croustillant." },
  { nom: "Straffe Hendrik", emoji: "🇧🇪", type: "Strong quadrupel", origine: "Belgique — Bruges", force: "9%", fa: "La « forte Henri » de la famille Van Houcke, à Bruges-médiévale." },
  { nom: "Brugse Zot Dubbel", emoji: "🇧🇪", type: "Dubbel brugeoise", origine: "Belgique — Bruges", force: "6%", fa: "Les « fous de Bruges » raillés par l'empereur Maximilien : le surnom est resté." },
  { nom: "Kwak", emoji: "🎻", type: "Strong amber ale", origine: "Belgique — Buggenhout", force: "8%", fa: "Le verre en forme de mousqueton s'attache au banc des cochers. Attache-toi." },
  { nom: "Poperings Hommelbier", emoji: "🇧🇪", type: "Bière au houblon", origine: "Belgique — Poperinge", force: "7%", fa: "Hommel = houblon en flamand : la capitale du houblon belge se boit." },
  { nom: "Hommel Ale", emoji: "🇧🇪", type: "Bière au houblon", origine: "Belgique — Poperinge", force: "7%", fa: "Brassée par la famille Van Eecke, l'autre ferme-houblonnière du coin." },
  { nom: "Lupulus", emoji: "🇧🇪", type: "Bière au houblon", origine: "Belgique — Achouffe", force: "8,5%", fa: "Brassée à l'eau des sources ardennaises : le houblon y est roi." },
  { nom: "Silly Saison", emoji: "🇧🇪", type: "Saison", origine: "Belgique — Silly", force: "5%", fa: "La saison des fermes du Hainaut, racontée par la brasserie de Silly." },
  { nom: "Saison Dupont", emoji: "🌾", type: "Saison", origine: "Belgique — Tourpes", force: "6,5%", fa: "La saison de référence mondiale, née pour désaltérer les moissons." },
  { nom: "Avec les Bons Vœux", emoji: "🇧🇪", type: "Saison forte", origine: "Belgique — Tourpes", force: "9,5%", fa: "La saison premium des Dupont : la carte de voeux se boit." },
  { nom: "La Merveille", emoji: "🇧🇪", type: "Saison", origine: "Belgique — Bah-d'Écaussinnes", force: "6%", fa: "Saison de la ferme-brasserie de Blaugies, au bord du bocage." },
  { nom: "Fantôme", emoji: "🦆", type: "Saison fantaisiste", origine: "Belgique — Soy", force: "8%", fa: "Dany Prignon brasse des saisons imprévisibles : chaque fût est une surprise." },
  { nom: "Taras Boulba", emoji: "🌳", type: "Bière hoppy", origine: "Belgique — Bruxelles", force: "4,5%", fa: "Nabokov sur l'étiquette, du houblon frais dans le verre : 4,5% de poésie." },
  { nom: "Zinnebir", emoji: "🇧🇪", type: "Bière de Senne", origine: "Belgique — Bruxelles", force: "6%", fa: "La Senne, rivière bruxelloise, donne son nom à cette ambrée croquante." },
  { nom: "XX Bitter", emoji: "🇧🇪", type: "Bière ultra-amère", origine: "Belgique — Dottignies", force: "6,2%", fa: "De Ranke l'a faite pour les fanatiques d'amertume : âpre et fière." },
  { nom: "Guldenberg", emoji: "🇧🇪", type: "Blonde d'abbaye ambrée", origine: "Belgique — Dottignies", force: "8,5%", fa: "L'autre bijou de De Ranke : douce, dorée, houblonnée à l'ancienne." },
  { nom: "De Ranke Kriek", emoji: "🇧🇪", type: "Kriek traditionnelle", origine: "Belgique — Dottignies", force: "6%", fa: "Des vraies cerises sur lambic, sans sirop : l'acidité franche." },
  { nom: "Wipers Times", emoji: "🇧🇪", type: "Bière ambrée", origine: "Belgique — Dottignies", force: "6%", fa: "Hommage au journal des tranchées de la Grande Guerre, brassée à l'anglaise." },
  { nom: "Troubadour Mocha Stout", emoji: "🇧🇪", type: "Stout au café", origine: "Belgique — Roulers", force: "8,2%", fa: "Stout à la belge : cacao et café, sans oublier d'être ambrée-forte." },
  { nom: "Bourgogne des Flandres", emoji: "🇧🇪", type: "Rouge des Flandres", origine: "Belgique — Bruges", force: "5%", fa: "Assemblage de lambic et de brune douce : le vin de Bourgogne, version bière." },
  { nom: "Rodenbach", emoji: "🍒", type: "Rouge des Flandres", origine: "Belgique — Roulers", force: "5,2%", fa: "Vieillie deux ans en fûts de chêne : acidité et cerise, signature des Flandres." },
  { nom: "Rodenbach Vintage", emoji: "🍒", type: "Rouge des Flandres", origine: "Belgique — Roulers", force: "7%", fa: "Fût unique, millésimé : le grand cru des rouges flamandes." },
  { nom: "Duchesse de Bourgogne", emoji: "👑", type: "Rouge des Flandres", origine: "Belgique — Oudenaarde", force: "6,2%", fa: "Vieillie 18 mois en chêne : la duchse trône sur les tables fines." },
  { nom: "Liefmans Goudenband", emoji: "🇧🇪", type: "Rouge-brune de garde", origine: "Belgique — Oudenaarde", force: "8%", fa: "Coupée à l'ancienne au couteau, tellement elle est épaisse." },
  { nom: "Liefmans Cuvée Brut", emoji: "🇧🇪", type: "Kriek brut", origine: "Belgique — Oudenaarde", force: "6%", fa: "Macérée aux cerises à la façon du champagne : la bulle en plus." },
  { nom: "Cantillon Gueuze", emoji: "🇧🇪", type: "Gueuze assemblée", origine: "Belgique — Bruxelles", force: "5%", fa: "Fermentée par les levures sauvages de l'air de Bruxelles, dans un grenier ouvert." },
  { nom: "Cantillon Kriek", emoji: "🇧🇪", type: "Kriek sur lambic", origine: "Belgique — Bruxelles", force: "5%", fa: "Deux cents grammes de cerises par litre : le fruit et l'acidité en duel." },
  { nom: "Cantillon Rosé de Gambrinus", emoji: "🇧🇪", type: "Framboise sur lambic", origine: "Belgique — Bruxelles", force: "5%", fa: "La framboise noble sur lambic d'un an : rose et mordante." },
  { nom: "Cantillon Fou' Foune", emoji: "🍑", type: "Abricot sur lambic", origine: "Belgique — Bruxelles", force: "5%", fa: "Des abricots du Roussillon sur lambic : la fée électrique du brasseur." },
  { nom: "3 Fonteinen Oude Geuze", emoji: "🇧🇪", type: "Gueuze traditionnelle", origine: "Belgique — Beersel", force: "6%", fa: "Assemblage de lambics d'un, deux et trois ans, en chruche de champagne." },
  { nom: "3 Fontainen Schaarbeekse Kriek", emoji: "🍒", type: "Kriek sauvage", origine: "Belgique — Beersel", force: "6,5%", fa: "Les petites cerises acides de Bruxelles, comme au bon vieux temps." },
  { nom: "Boon Oude Geuze Mariage Parfait", emoji: "🇧🇪", type: "Gueuze de garde", origine: "Belgique — Lembeek", force: "6,5%", fa: "Le « mariage parfait » : trois ans de fût avant la bouteille." },
  { nom: "Boon Kriek", emoji: "🇧🇪", type: "Kriek sur lambic", origine: "Belgique — Lembeek", force: "4,5%", fa: "La kriek douce-acide de la brasserie-musée de Lembeek." },
  { nom: "Lindemans Gueuze", emoji: "🇧🇪", type: "Gueuze douce", origine: "Belgique — Vlezenbeek", force: "4%", fa: "La gueuze filtrée et sucrée : la porte d'entrée du monde lambic." },
  { nom: "Lindemans Kriek", emoji: "🇧🇪", type: "Kriek douce", origine: "Belgique — Vlezenbeek", force: "4%", fa: "La kriex accessible : parfait pour convertir les sceptiques." },
  { nom: "Lindemans Framboise", emoji: "🇧🇪", type: "Framboise douce", origine: "Belgique — Vlezenbeek", force: "4%", fa: "Sirop de framboise ou pas, elle reste sur lambic véritable." },
  { nom: "Mort Subite Oude Gueuze", emoji: "⚡", type: "Gueuze traditionnelle", origine: "Belgique — Kobbegem", force: "5,5%", fa: "« Mort subite » : le nom du café de Bruxelles où on la buvait." },
  { nom: "Belle-Vue Gueuze", emoji: "🇧🇪", type: "Gueuze accessible", origine: "Belgique — Bruxelles", force: "5%", fa: "La gueuze du dimanche : douce, citronnée, à la mousse fine." },
  { nom: "Oud Beersel Oude Geuze", emoji: "🇧🇪", type: "Gueuze traditionnelle", origine: "Belgique — Beersel", force: "6%", fa: "De la gueuze de comptoir, comme à l'école flamande." },
  { nom: "Tilquin Gueuze", emoji: "🇧🇪", type: "Gueuze d'assemblage", origine: "Belgique — Bierghes", force: "6,5%", fa: "Le dernier « blendeur » de gueuze indépendant : il achète le lambic, pas la brasserie." },
  { nom: "Hanssens Oude Gueuze", emoji: "🇧🇪", type: "Gueuze traditionnelle", origine: "Belgique — Dworp", force: "6%", fa: "Une des plus acides du pays : les dents frémissent, le coeur aussi." },
  { nom: "Girardin Gueuze", emoji: "🇧🇪", type: "Gueuze traditionnelle", origine: "Belgique — Sint-Ulriks-Kapelle", force: "5%", fa: "La girafe de l'étiquette : une gueuze rustique du Brabant flamand." },
  { nom: "De Cam Oude Geuze", emoji: "🇧🇪", type: "Gueuze d'assemblage", origine: "Belgique — Gooik", force: "6%", fa: "Assemblée à la ferme, sur les hauts plateaux du Pajottenland." },
  { nom: "Hoegaarden", emoji: "🍋", type: "Blanche", origine: "Belgique — Hoegaarden", force: "4,9%", fa: "La blanche au coriandre et à l'écorce d'orange : inventée par Pierre Celis." },
  { nom: "Blanche de Namur", emoji: "🇧🇪", type: "Blanche", origine: "Belgique — Namur", force: "4,5%", fa: "Née de la légende de la « Blonde de Namur », princesse française du XVe." },
  { nom: "Brugs Tarwebier", emoji: "🇧🇪", type: "Blanche brugeoise", origine: "Belgique — Bruges", force: "4,6%", fa: "La « blé-bière » de Bruges : rafraîchissante après le Minnewater." },
  { nom: "Weihenstephaner", emoji: "🏰", type: "Hefeweizen", origine: "Allemagne — Freising", force: "5,4%", fa: "La plus ancienne brasserie du monde (1040) : elle a survécu à tout." },
  { nom: "Weihenstephaner Vitus", emoji: "🏰", type: "Weizenbock", origine: "Allemagne — Freising", force: "7,7%", fa: "Un doppelbock de froment : banane et clou de girofle dopés." },
  { nom: "Schneider Weisse Tap 6", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Kelheim", force: "5,4%", fa: "Georg Schneider garde le froment munichois vivant depuis 1872." },
  { nom: "Aventinus", emoji: "🇩🇪", type: "Weizen doppelbock", origine: "Allemagne — Kelheim", force: "8,2%", fa: "Le plus vieux doppelbock de froment de Bavière : complexe et velouté." },
  { nom: "Schneider Edel Weisse", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Kelheim", force: "6,2%", fa: "La version tonique et épicée du froment Schneider." },
  { nom: "Erdinger Weissbier", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Erding", force: "5,6%", fa: "La weissbier « du champion » : sport et bière, le contrat est signé." },
  { nom: "Franziskaner", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Munich", force: "5%", fa: "Le moine franciscain sur l'étiquette : le froment du centre de Munich." },
  { nom: "Maisel Weisse", emoji: "🇩🇪", type: "Weizen", origine: "Allemagne — Bayreuth", force: "7%", fa: "La « perle de Weisse » de Bayreuth : fruitée, charnue, généreuse." },
  { nom: "Ayinger Bräu Weisse", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Aying", force: "5,1%", fa: "Brassée dans le village d'Aying : la mousse est de la crème." },
  { nom: "Schöfferhofer Weizen", emoji: "🇩🇪", type: "Weizen", origine: "Allemagne — Mayence", force: "4,8%", fa: "Le froment de Mayence, celui qu'on trouve partout et qu'on reloue toujours." },
  { nom: "Augustiner Helles", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "5,2%", fa: "La favorite des Munichois : le robinet à bière tire à la verticale, pression par gravité." },
  { nom: "Augustiner Edelstoff", emoji: "🇩🇪", type: "Export helles", origine: "Allemagne — Munich", force: "5,6%", fa: "« Edelstoff » : le trésor de la brasserie des Augustins, en bouteille uniquement." },
  { nom: "Augustiner Dunkel", emoji: "🇩🇪", type: "Dunkel", origine: "Allemagne — Munich", force: "5%", fa: "La brune de Munich par excellence : pain grillé et caramel." },
  { nom: "Tegernseer Spezial", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Tegernsee", force: "5,4%", fa: "La brasserie de l'ancienne abbaye de Tegernsee : le lac, les monts, la bière." },
  { nom: "Jever Pils", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Jever", force: "4,9%", fa: "La « pils au goût » du nord : sèche, herbacée, nette comme un vent de mer." },
  { nom: "Warsteiner", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Warstein", force: "4,8%", fa: "« La reine des pils » d'après la pub : la bombe allemande qu'on trouve partout." },
  { nom: "Radeberger", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Radeberger", force: "4,8%", fa: "La pils favorite des Allemands de l'Est, née sous Bismarck." },
  { nom: "Bitburger", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Bitburg", force: "4,8%", fa: "« Bitte ein Bit » : le slogan le plus reprenable d'Allemagne." },
  { nom: "Veltins", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Meschede", force: "4,8%", fa: "La pils du Sauerland, dans des bouteilles toujours très froides." },
  { nom: "Flensburger", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Flensbourg", force: "4,8%", fa: "Le clapot du bouchon à clapet (« plop ») : on l'entend avant de la boire." },
  { nom: "Rothaus Tannenzäpfle", emoji: "🌲", type: "Pilsner", origine: "Allemagne — Forêt-Noire", force: "5,1%", fa: "La « petite pomme de pin » de la Forêt-Noire : née dans une région de sapins." },
  { nom: "Kneitinger Pils", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Ratisbonne", force: "4,8%", fa: "La pils de Ratisbonne, la préférée des puristes bavarois." },
  { nom: "Hofbräu Original", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "5,5%", fa: "La brasserie du duc de Bavière : on y boit dans des chopes d'un litre." },
  { nom: "Löwenbräu Original", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "5,2%", fa: "Le lion de Munich brasse depuis 1383 : la bière de l'Oktoberfest." },
  { nom: "Paulaner Münchner Hell", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "4,9%", fa: "Les moines paulaniers brassaient pour survivre : leur helles est sainte." },
  { nom: "Paulaner Salvator", emoji: "🍺", type: "Doppelbock", origine: "Allemagne — Munich", force: "7,9%", fa: "Le « Sauveur » : les moines jeûnaient avec, d'où le nom. Sacrée excuse." },
  { nom: "Ayinger Celebrator", emoji: "🇩🇪", type: "Doppelbock", origine: "Allemagne — Aying", force: "6,7%", fa: "La médaille du bouc sur l'étiquette : le doppelbock de référence." },
  { nom: "Andechser Doppelbock", emoji: "⛪", type: "Doppelbock", origine: "Allemagne — Andechs", force: "7,1%", fa: "Brassée par les bénédictins de la colline d'Andechs : pèlerinage gustatif." },
  { nom: "Korbinian", emoji: "👑", type: "Doppelbock", origine: "Allemagne — Füssen", force: "9,2%", fa: "Nommée d'après saint Korbinian, l'évêque à l'ours : la légende et la bière." },
  { nom: "König Ludwig Weiss", emoji: "🇩🇪", type: "Weizen", origine: "Allemagne — Füssen", force: "5,5%", fa: "La brasserie royale de Hohenschwangau, face au château de Louis II." },
  { nom: "EKU 28", emoji: "🔥", type: "Doppelbock fort", origine: "Allemagne — Erlangen", force: "11%", fa: "Autrefois la bière la plus forte du monde : on la sirote comme un digestif." },
  { nom: "Kulmbacher Eisbock", emoji: "🧊", type: "Eisbock", origine: "Allemagne — Kulmbach", force: "9,2%", fa: "La légende : un tonneau oublié dehors, la glace enlevée, l'alcool concentré." },
  { nom: "Schneider Aventinus Eisbock", emoji: "🇩🇪", type: "Weizen eisbock", origine: "Allemagne — Kelheim", force: "12%", fa: "L'Aventinus congelé à mi-fermentation : banane, chocolat et Figuier du Brésil." },
  { nom: "Einbecker Mai-Ur-Bock", emoji: "🌱", type: "Bock de mai", origine: "Allemagne — Einbeck", force: "7%", fa: "Einbeck est la mère des bocks : son nom a donné « Bock » en bavarois." },
  { nom: "Schlenkerla Märzen", emoji: "🔥", type: "Rauchbier", origine: "Allemagne — Bamberg", force: "5,4%", fa: "Le malt fumé au bois de hêtre : le jambon de la bière, à Bamberg on adore." },
  { nom: "Schlenkerla Weizen", emoji: "🔥", type: "Rauchbier", origine: "Allemagne — Bamberg", force: "5,2%", fa: "Un froment fumé : la boulangerie et le comptoir dans le même verre." },
  { nom: "Spezial Rauchbier", emoji: "🔥", type: "Rauchbier", origine: "Allemagne — Bamberg", force: "5%", fa: "L'autre fumée de Bamberg, plus douce : la ville en compte deux écoles." },
  { nom: "Diebels Alt", emoji: "🇩🇪", type: "Altbier", origine: "Allemagne — Issum", force: "4,9%", fa: "La « voleuse » : l'alt de référence, rouge-brune et sèche." },
  { nom: "Uerige Alt", emoji: "🇩🇪", type: "Altbier", origine: "Allemagne — Düsseldorf", force: "4,3%", fa: "La brasserie d' « Uerige » le savoureux aigre : alt au comptoir, tournée minuscule." },
  { nom: "Schumacher Alt", emoji: "🇩🇪", type: "Altbier", origine: "Allemagne — Düsseldorf", force: "4,5%", fa: "La plus ancienne maison d'alt (1838) : on y boit debout, serrés, heureux." },
  { nom: "Füchschen Alt", emoji: "🇩🇪", type: "Altbier", origine: "Allemagne — Düsseldorf", force: "4,5%", fa: "Le petit renard du vieux Düsseldorf : amère et rustique." },
  { nom: "Gaffel Kölsch", emoji: "🚂", type: "Kölsch", origine: "Allemagne — Cologne", force: "4,8%", fa: "La kölsch de référence au chardon : tant que le verre est plein, on resserve." },
  { nom: "Reissdorf Kölsch", emoji: "🚂", type: "Kölsch", origine: "Allemagne — Cologne", force: "4,8%", fa: "La kölsch la plus bue de Cologne : 20 cl à la fois, à la folie douce." },
  { nom: "Früh Kölsch", emoji: "🚂", type: "Kölsch", origine: "Allemagne — Cologne", force: "4,8%", fa: "La kölsch du vieux-port, à côté de la cathédrale : un pèlerinage." },
  { nom: "Mühlen Kölsch", emoji: "🚂", type: "Kölsch", origine: "Allemagne — Cologne", force: "4,8%", fa: "Brassée au moulin de la ville : la plus confidentielle des kölsch." },
  { nom: "Berliner Kindl Weisse", emoji: "🍋", type: "Berliner Weisse", origine: "Allemagne — Berlin", force: "2,8%", fa: "La bière des rois de Prusse, si acide qu'on y ajoute un schuss de sirop." },
  { nom: "Pinkus Alt", emoji: "🇩🇪", type: "Altbier bio", origine: "Allemagne — Münster", force: "4,5%", fa: "La brasserie bio avant l'heure : le goût du vrai, depuis 1816." },
  { nom: "Weltenburger Barock Dunkel", emoji: "⛪", type: "Dunkel", origine: "Allemagne — Kelheim", force: "4,9%", fa: "L'abbaye revendique le titre de plus vieille brasserie de monastère du monde." },
  { nom: "Altbairisch Dunkel", emoji: "🇩🇪", type: "Dunkel", origine: "Allemagne — Aying", force: "5%", fa: "La brune de la vieille Bavière : pain de seigle, pruneau, douceur." },
  { nom: "Köstritzer Schwarzbier", emoji: "⚫", type: "Schwarzbier", origine: "Allemagne — Bad Köstritz", force: "4,8%", fa: "La noire de Goethe : le poète buvait ce « velours noir » à l'écriture." },
  { nom: "Goslarer Gose", emoji: "🌀", type: "Gose", origine: "Allemagne — Goslar", force: "4,5%", fa: "Acide, salée, coriandrée : la bière que le Moyen Âge a oubliée puis ressuscitée." },
  { nom: "Kuchlbauer Weisse", emoji: "🏰", type: "Weizen", origine: "Allemagne — Abensberg", force: "5,6%", fa: "Sa tour dorée a été dessinée par Hundertwasser : l'art avec la weissbier." },
  { nom: "Neumarkter Lammsbräu", emoji: "🌱", type: "Bio helles", origine: "Allemagne — Neumarkt", force: "5%", fa: "La pionnière bio allemande : la bière du respect, depuis 1979." },
  { nom: "Beck's", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Brême", force: "4,9%", fa: "La bouteille verte ne sort de Brême que pour l'export : en ville, on la boit en fût." },
  { nom: "St. Georgen Bräu Kellerbier", emoji: "🌾", type: "Kellerbier", origine: "Allemagne — Buttenheim", force: "4,9%", fa: "Brassée « sur lie » à l'ombre des caves : la bière de cave parfaite." },
  { nom: "Fischer Tradition", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Alsace, Strasbourg", force: "6%", fa: "La bière de garde : brassée l'hiver, gardée des mois pour tenir l'été. L'Alsace brassicole." },
  { nom: "Adelscott", emoji: "🇫🇷", type: "Bière fumée au malt whisky", origine: "France — Schiltigheim", force: "6,5%", fa: "Malt fumé au tourbe, façon whisky : l'Alsace en mode Écosse." },
  { nom: "Pelforth Blonde", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Lyon", force: "6,8%", fa: "« Pel mon dieu » : le pélican de Pelforth a conquis les bistrots français." },
  { nom: "Pelforth Brune", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Lyon", force: "6,6%", fa: "La brune des années 60 : les papas la réclament encore au comptoir." },
  { nom: "3 Monts", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Saint-Sylvestre", force: "8,5%", fa: "La gardienne du Nord : brassée dans les hauts de Flandre, taillée pour vieillir." },
  { nom: "La Goudale", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Douai", force: "7,2%", fa: "Conçue pour payer des « goudales » de dettes : la bière des comtes de Flandre." },
  { nom: "Jenlain Ambrée", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Jenlain", force: "7,5%", fa: "La bière du Nord qui a relancé la France brassicole en 1974." },
  { nom: "La Choulette Ambrée", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Hargnies", force: "5,9%", fa: "Brassée dans une ancienne ferme-brasserie du Nord : le retour du goût." },
  { nom: "Ch'ti Blonde", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Loos-en-Gohelle", force: "6,4%", fa: "Le Ch'ti à la bière : bienvenue au bistrot du Nord." },
  { nom: "Ch'ti Rousse", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Loos-en-Gohelle", force: "6,4%", fa: "La rousse des mines : le charbon dans le verre, en mieux." },
  { nom: "Mont des Cats", emoji: "⛪", type: "Trappiste", origine: "France — Godewaersvelde", force: "7,6%", fa: "L'unique trappiste française : brassée jadis à l'abbaye, rebaptisée en 2016." },
  { nom: "Bière du Démon", emoji: "😈", type: "Bière forte", origine: "France — Riom", force: "12%", fa: "12% d'alcool : le démon français, à respecter avant de siffler." },
  { nom: "Cervoise Lancelot", emoji: "🌰", type: "Cervoise", origine: "France — Bretagne, Josselin", force: "5,5%", fa: "La cervoise des Gaulois, brassée au foyer d'un château breton." },
  { nom: "Telenn Du", emoji: "🖤", type: "Bière au blé noir", origine: "France — Bretagne, Josselin", force: "4,8%", fa: "Du sarrasin breton : la galette se boit aussi." },
  { nom: "Britt Blonde", emoji: "🇫🇷", type: "Blonde de blé", origine: "France — Bretagne, Trégunc", force: "4,5%", fa: "Le breton la boit à l'apéro : le froment armoricain." },
  { nom: "Britt Rousse", emoji: "🇫🇷", type: "Rousse", origine: "France — Bretagne, Trégunc", force: "5%", fa: "La rousse bretonne : caramel et beurre demi-sel (presque)." },
  { nom: "Meteor Pils", emoji: "🇫🇷", type: "Pilsner", origine: "France — Hochfelden", force: "5%", fa: "L'indépendante d'Alsace : la dernière grande brasserie familiale." },
  { nom: "Meteor Blanc de Blancs", emoji: "🇫🇷", type: "Blanche", origine: "France — Hochfelden", force: "5,5%", fa: "Blanche alsacienne au froment : la couronne des vallées vosgiennes." },
  { nom: "Ninkasi IPA", emoji: "🇫🇷", type: "IPA", origine: "France — Lyon", force: "6%", fa: "Née à Lyon, ville de Ninkasi la déesse sumérienne de la bière." },
  { nom: "Deck & Donohue East Indie Pale Ale", emoji: "🇫🇷", type: "IPA", origine: "France — Montreuil", force: "6%", fa: "Deux Américains à Paris : l'IPA de la capitale redevient honnête." },
  { nom: "La Goutte d'Or", emoji: "🇫🇷", type: "Blonde", origine: "France — Paris 18e", force: "6%", fa: "Brassée dans la Goutte d'Or, comme le vin du même nom jadis." },
  { nom: "Bière du Mont Blanc — La Blonde", emoji: "🏔️", type: "Blonde", origine: "France — Savoie", force: "5%", fa: "Brassée avec l'eau des Alpes : la menthe en moins, la mousse en plus." },
  { nom: "Bière du Mont Blanc — La Rousse", emoji: "🏔️", type: "Rousse", origine: "France — Savoie", force: "6%", fa: "La rousse alpine : de l'eau de fonte des neiges en bouteille." },
  { nom: "Mistral Gagnal", emoji: "⛵", type: "Blonde", origine: "France — Marseille", force: "6%", fa: "Le mistral dans les voiles et dans le comptoir : Marseille brassicole." },
  { nom: "Anosteké Blonde", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Douai", force: "6,5%", fa: "Le refrain des fêtes du Nord : « Anosteké ! » comme disent les Ch'tis." },
  { nom: "Pietra", emoji: "🌰", type: "Bière à la châtaigne", origine: "France — Corse, Furiani", force: "5%", fa: "Brassée avec de la farine de châtaigne corse : la bière du maquis." },
  { nom: "Colomba", emoji: "🕊️", type: "Blanche corse", origine: "France — Corse, Furiani", force: "5%", fa: "La blanche de Pâques en Corse, à la fleur d'oranger." },
  { nom: "Guinness", emoji: "☘️", type: "Stout", origine: "Irlande — Dublin", force: "4,2%", fa: "Bail de 9 000 ans signé par Arthur Guinness. Le père avait laissé 100 £, il les a mis dans la bière." },
  { nom: "Guinness Foreign Extra", emoji: "☘️", type: "Stout", origine: "Irlande — Dublin", force: "7,5%", fa: "La version forte exportée jadis jusqu'aux tropiques : celle qui a conquis l'Afrique de l'Ouest." },
  { nom: "Murphy's", emoji: "🇮🇪", type: "Stout", origine: "Irlande — Cork", force: "4%", fa: "La douce concurrente de la Guinness : moins amère, plus crémeuse." },
  { nom: "Beamish", emoji: "🇮🇪", type: "Stout", origine: "Irlande — Cork", force: "4%", fa: "Le troisième mousquetaire des stouts irlandais, fidèle à Cork." },
  { nom: "Smithwick's", emoji: "🇮🇪", type: "Rousse irlandaise", origine: "Irlande — Kilkenny", force: "4,5%", fa: "La rousse du monastère de Kilkenny, plus vieille brasserie d'Irlande." },
  { nom: "O'Hara's Irish Stout", emoji: "🇮🇪", type: "Stout", origine: "Irlande — Carlow", force: "4,4%", fa: "La stout des artisans de Carlow : le revival irlandais du vrai goût." },
  { nom: "Fuller's London Pride", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Londres", force: "4,7%", fa: "La fierté de Londres depuis 1959 : l'amertume est une politesse." },
  { nom: "Fuller's ESB", emoji: "🇬🇧", type: "Strong bitter", origine: "Angleterre — Londres", force: "5,5%", fa: "La « Extra Special Bitter » par excellence : une championne multicroisée." },
  { nom: "Fuller's London Porter", emoji: "🇬🇧", type: "Porter", origine: "Angleterre — Londres", force: "5,4%", fa: "Le style du port de Londres, ressuscité à Chiswick : noir, doux, profond." },
  { nom: "Fuller's Vintage Ale", emoji: "🇬🇧", type: "Barleywine", origine: "Angleterre — Londres", force: "8,5%", fa: "Millésimée chaque année : on la garde comme un grand vin de Bordeaux." },
  { nom: "Fuller's 1845", emoji: "🇬🇧", type: "Strong ale", origine: "Angleterre — Londres", force: "6,1%", fa: "Brassée pour l'anniversaire de la brasserie : la bouteille à cire rouge." },
  { nom: "Samuel Smith Oatmeal Stout", emoji: "🇬🇧", type: "Stout à l'avoine", origine: "Angleterre — Tadcaster", force: "5%", fa: "L'avoine dans le stout : la texture de velours, brasser depuis 1758." },
  { nom: "Samuel Smith Taddy Porter", emoji: "🇬🇧", type: "Porter", origine: "Angleterre — Tadcaster", force: "5,4%", fa: "Le porter des mineurs du Yorkshire : noir et nourrissant." },
  { nom: "Samuel Smith Old Brewery Pale", emoji: "🇬🇧", type: "Pale ale", origine: "Angleterre — Tadcaster", force: "5%", fa: "Brassée encore en fûts de pierre de Yorkshire : la tradition en bouteille." },
  { nom: "Theakston Old Peculier", emoji: "🇬🇧", type: "Old ale", origine: "Angleterre — Masham", force: "5,6%", fa: "« Peculier » : un mot du droit ecclésiastique, une bière au goût de pruneau." },
  { nom: "Robinson's Old Tom", emoji: "🇬🇧", type: "Barleywine", origine: "Angleterre — Stockport", force: "8,5%", fa: "Élue plusieurs fois « meilleure bière du monde » : le chat sur l'étiquette a bon goût." },
  { nom: "Young's Double Chocolate Stout", emoji: "🍫", type: "Stout chocolaté", origine: "Angleterre — Londres", force: "5%", fa: "Chocolat noir et vanille dans un stout : le dessert des soirs anglais." },
  { nom: "Hook Norton Old Hooky", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Oxfordshire", force: "4,3%", fa: "Brassée avec une machine à vapeur de 1899 : le village se boit à la pompe." },
  { nom: "Timothy Taylor Landlord", emoji: "🇬🇧", type: "Pale ale", origine: "Angleterre — Keighley", force: "4,3%", fa: "La préférée des buveurs anglais : elle a même converti Hollywood." },
  { nom: "St Austell Tribute", emoji: "🇬🇧", type: "Pale ale", origine: "Angleterre — Cornouailles", force: "4,2%", fa: "Brassée pour un eclipse solaire en 1999 : la Cornouailles en fût." },
  { nom: "Wadworth 6X", emoji: "🇬🇧", type: "Strong bitter", origine: "Angleterre — Devizes", force: "6%", fa: "Les livraison se font encore par cheval dans Devizes : la 6X du cocher." },
  { nom: "Shepherd Neame Spitfire", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Faversham", force: "4,5%", fa: "Née pour les 50 ans de la bataille d'Angleterre : l'humour en bouteille." },
  { nom: "Bishop's Finger", emoji: "🇬🇧", type: "Strong ale", origine: "Angleterre — Faversham", force: "5,4%", fa: "Le doigt de l'évêque indique le chemin de la brasserie (vraiment)." },
  { nom: "Harvey's Sussex Best", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Lewes", force: "4%", fa: "Le bitter du Sussex, servi à la parfaite température de cave." },
  { nom: "Adnams Southwold", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Suffolk", force: "4,3%", fa: "La bière des côtes du Suffolk : les mouettes la réclament aussi." },
  { nom: "Hobgoblin", emoji: "🧙", type: "Rousse", origine: "Angleterre — Witney", force: "5,2%", fa: "Le gobelin de Wychwood : la rousse qui a conquis les étudiants anglais." },
  { nom: "Bombardier", emoji: "🇬🇧", type: "English bitter", origine: "Angleterre — Bedford", force: "5,2%", fa: "« English Premium Bitter » : la bière qui se boit comme un hymne." },
  { nom: "Black Sheep Riggwelter", emoji: "🇬🇧", type: "Strong dark ale", origine: "Angleterre — Masham", force: "5,7%", fa: "« Riggwelter » : mot du Yorkshire pour une brebis sur le dos. On comprend après la pinte." },
  { nom: "Innis & Gunn Original", emoji: "🛢️", type: "Bière vieillie en fût", origine: "Écosse — Édimbourg", force: "6,6%", fa: "Vieillie en ex-fûts de whisky : l'Ecosse entière dans une bouteille." },
  { nom: "Traquair House Ale", emoji: "🏰", type: "Strong scotch ale", origine: "Écosse — Innerleithen", force: "7,2%", fa: "Brassée dans la plus ancienne maison habitée d'Ecosse, depuis 1965." },
  { nom: "Fraoch", emoji: "🌸", type: "Heather ale", origine: "Écosse — Glasgow", force: "5%", fa: "Brassée à la bruyère : la recette des Pictes, ressuscitée par les frères Williams." },
  { nom: "BrewDog Punk IPA", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", type: "IPA", origine: "Écosse — Ellon", force: "5,4%", fa: "La punk qui a déridé le Royaume : l'amertume comme manifeste." },
  { nom: "Thornbridge Jaipur", emoji: "🇬🇧", type: "IPA", origine: "Angleterre — Bakewell", force: "5,9%", fa: "L'IPA de la nouvelle vague anglaise : florale, sèche, multiple médaillée." },
  { nom: "Meantime London Pale Ale", emoji: "🇬🇧", type: "Pale ale", origine: "Angleterre — Londres", force: "4,3%", fa: "La pale ale de Greenwich : le méridien de l'amertume britannique." },
  { nom: "Bass Pale Ale", emoji: "🔺", type: "Pale ale", origine: "Angleterre — Burton-upon-Trent", force: "5,2%", fa: "Le triangle rouge : première marque déposée du Royaume-Uni (1876)." },
  { nom: "Harviestoun Bitter & Twisted", emoji: "🇬🇧", type: "Bitter", origine: "Écosse — Alva", force: "4,2%", fa: "Agrumes et amertume sèche : le twist du nom est dans le verre." },
  { nom: "Newcastle Brown Ale", emoji: "🐕", type: "Brown ale", origine: "Angleterre — Newcastle", force: "4,7%", fa: "La « Nukey Brown » des docks : la mousse des travailleurs du Nord." },
  { nom: "Boddingtons", emoji: "🇬🇧", type: "Cream ale", origine: "Angleterre — Manchester", force: "3,5%", fa: "« La crème de Manchester » : le nitro donne une texture de laitue onctueuse." },
  { nom: "Tetley's", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Leeds", force: "3,8%", fa: "Le Yorkshire pudding se boit aussi : le bitter de Leeds, très crémeux." },
  { nom: "Sierra Nevada Pale Ale", emoji: "🇺🇸", type: "Pale ale", origine: "États-Unis — Californie", force: "5,6%", fa: "Celle qui a lancé la révolution craft américaine en 1980 : cascade hops forever." },
  { nom: "Sierra Nevada Torpedo", emoji: "🇺🇸", type: "IPA", origine: "États-Unis — Californie", force: "7,2%", fa: "La « Torpedo » : inventée pour injecter le houblon à sec en continu." },
  { nom: "Goose Island IPA", emoji: "🇺🇸", type: "IPA", origine: "États-Unis — Chicago", force: "5,9%", fa: "L'IPA de Chicago, rachetée par AB InBev : les puristes grinceront, elle reste bonne." },
  { nom: "Goose Island Bourbon County", emoji: "🇺🇸", type: "Stout vieilli en bourbon", origine: "États-Unis — Chicago", force: "13%", fa: "Vieillie en fûts de whiskey : chaque Black Friday, les files d'attente s'allongent." },
  { nom: "Sam Adams Boston Lager", emoji: "🇺🇸", type: "Lager", origine: "États-Unis — Boston", force: "4,8%", fa: "Celle qui a prouvé aux Américains que la bière pouvait avoir du goût." },
  { nom: "Sam Adams Utopias", emoji: "🇺🇸", type: "Bière extrême", origine: "États-Unis — Boston", force: "28%", fa: "28% d'alcool, pas de distillation : interdite dans certains États. Le péché mignon des collectionneurs." },
  { nom: "Brooklyn Lager", emoji: "🇺🇸", type: "Lager", origine: "États-Unis — New York", force: "5,2%", fa: "La lager du retour : New York a retrouvé sa bière en 1988." },
  { nom: "Lagunitas IPA", emoji: "🇺🇸", type: "IPA", origine: "États-Unis — Californie", force: "6,2%", fa: "Brassée par des zouaves de Petaluma : l'IA de la désinvolture californienne." },
  { nom: "Lagunitas A Little Sumpin' Sumpin'", emoji: "🇺🇸", type: "Pale ale au froment", origine: "États-Unis — Californie", force: "7,1%", fa: "« Un petit quelque chose » : houblon et froment, le cocktail californien." },
  { nom: "Stone IPA", emoji: "🗿", type: "IPA", origine: "États-Unis — Californie", force: "6,9%", fa: "« Fier. Arrogant. Pas pour tout le monde. » : le gargo en bouteille." },
  { nom: "Ballast Point Sculpin", emoji: "🐟", type: "IPA", origine: "États-Unis — San Diego", force: "7%", fa: "Le poisson-scorpion de San Diego : l'IPA qui a mis la ville sur la carte." },
  { nom: "Russian River Pliny the Elder", emoji: "🌿", type: "Double IPA", origine: "États-Unis — Californie", force: "8%", fa: "Les files d'attente devant la brasserie sont légendaires : la double IPA de référence." },
  { nom: "Dogfish Head 60 Minute", emoji: "🦺", type: "IPA", origine: "États-Unis — Delaware", force: "6%", fa: "Houblonnée 60 minutes en continu : l'IPA des érudits." },
  { nom: "Dogfish Head 120 Minute", emoji: "⏱️", type: "IPA extrême", origine: "États-Unis — Delaware", force: "18%", fa: "18% et toujours debout : le monstre à siroter comme un porto." },
  { nom: "Bell's Two Hearted", emoji: "🎣", type: "IPA", origine: "États-Unis — Michigan", force: "7%", fa: "La rivière à truites de Hemingway : l'IPA parfaite d'après les concours." },
  { nom: "New Belgium Fat Tire", emoji: "🚂", type: "Amber ale", origine: "États-Unis — Colorado", force: "5,2%", fa: "Nommée d'après le vélo du fondateur en France : l'amber la plus sympa des States." },
  { nom: "Anchor Steam", emoji: "🌉", type: "Steam beer", origine: "États-Unis — San Francisco", force: "4,9%", fa: "Fermentée à la vapeur sur les toits de San Francisco depuis 1896." },
  { nom: "The Alchemist Heady Topper", emoji: "⚡", type: "Double IPA", origine: "États-Unis — Vermont", force: "8%", fa: "Vendue uniquement à la brasserie, en canette : le graal des pèlerins houblonnés." },
  { nom: "Boulevard Tank 7", emoji: "🌻", type: "Saison américaine", origine: "États-Unis — Kansas City", force: "8,5%", fa: "La saison des Américains : née d'un fût « raté » devenu culte." },
  { nom: "Victory Prima Pils", emoji: "🇺🇸", type: "Pilsner", origine: "États-Unis — Pennsylvanie", force: "5,3%", fa: "La pils américaine du vrai : sèche, florale, fidèle à la vieille Europe." },
  { nom: "New Glarus Spotted Cow", emoji: "🐄", type: "Cream ale", origine: "États-Unis — Wisconsin", force: "4,8%", fa: "Introuvable hors du Wisconsin : le secret le mieux gardé du Middle West." },
  { nom: "Left Hand Milk Stout", emoji: "🥛", type: "Stout au lactose", origine: "États-Unis — Colorado", force: "6%", fa: "Le lactose adoucit le noir : la texture de lait, la couleur de nuit." },
  { nom: "Oskar Blues Dale's Pale Ale", emoji: "🎸", type: "Pale ale en canette", origine: "États-Unis — Colorado", force: "6,5%", fa: "La première craft en canette (2002) : « canned beer is good » disaient-ils." },
  { nom: "Pabst Blue Ribbon", emoji: "🏆", type: "Lager", origine: "États-Unis — Milwaukee", force: "4,7%", fa: "Ribbon bleu gagné en 1893, ressortie du placard par les hipsters." },
  { nom: "Blue Moon", emoji: "🌙", type: "Blanche", origine: "États-Unis — Colorado", force: "5,4%", fa: "La blanche des Rocheuses, avec sa rondelle d'orange obligatoire." },
  { nom: "Deschutes Fresh Squeezed", emoji: "🍊", type: "IPA", origine: "États-Unis — Oregon", force: "6,4%", fa: "Pressée du jour, comme son nom l'indique : l'Oregon en agrumes." },
  { nom: "Pilsner Urquell", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — Plzeň", force: "4,4%", fa: "La toute première pilsner (1842). Toutes les blondes du monde descendent d'elle." },
  { nom: "Budweiser Budvar", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — České Budějovice", force: "5%", fa: "La « vraie » Budweiser tchèque : le procès avec l'Américaine dure depuis 1907." },
  { nom: "Budvar Dark", emoji: "🇨🇿", type: "Dunkel tchèque", origine: "Tchéquie — České Budějovice", force: "4,7%", fa: "La noire de Budvar : du caramel de malt, de la douceur, du grand art." },
  { nom: "Kozel", emoji: "🐐", type: "Pilsner", origine: "Tchéquie — Velké Popovice", force: "4,6%", fa: "Le bouc sur l'étiquette, gardien du village brassicole." },
  { nom: "Kozel Černý", emoji: "🐐", type: "Dunkel", origine: "Tchéquie — Velké Popovice", force: "3,8%", fa: "La noire du bouc : légère, café, à boire en pinte tchèque." },
  { nom: "Staropramen", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — Prague", force: "5%", fa: "La bière des bars de Prague : le « grand toast » du Smíchov." },
  { nom: "Bernard", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — Humpolec", force: "5%", fa: "Brassée avec de l'eau de source de Bohême-Moravie : non filtrée en version «Family»." },
  { nom: "Krušovice", emoji: "🇨🇿", type: "Lager", origine: "Tchéquie — Krušovice", force: "5%", fa: "La bière des rois de Bohême, servie à la cour depuis le XVIe." },
  { nom: "U Fleků", emoji: "🕰️", type: "Dunkel de brasserie", origine: "Tchéquie — Prague", force: "5%", fa: "Brassée sur place à Prague depuis 1499 : le plus vieux comptoir de la ville." },
  { nom: "Primátor", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — Náchod", force: "5%", fa: "La bière de la forteresse de Náchod : la garde du goût." },
  { nom: "Heineken", emoji: "🇳🇱", type: "Lager", origine: "Pays-Bas — Amsterdam", force: "5%", fa: "La mousse « vedette » : le brasseur a inventé la levure A, il faut bien la boire." },
  { nom: "La Trappe Quadrupel", emoji: "⛪", type: "Trappiste quadrupel", origine: "Pays-Bas — Berkel-Enschot", force: "10%", fa: "La quadrupel mère : née à Koningshoeven, forte comme la foi des moines." },
  { nom: "La Trappe Dubbel", emoji: "⛪", type: "Trappiste dubbel", origine: "Pays-Bas — Berkel-Enschot", force: "7%", fa: "La dubbel des moines néerlandais : le seul monastère trappiste du pays." },
  { nom: "La Trappe Bockbier", emoji: "⛪", type: "Trappiste bock", origine: "Pays-Bas — Berkel-Enschot", force: "7%", fa: "La bock des moines : brassée une fois l'an, l'automne en bouteille." },
  { nom: "Zundert", emoji: "⛪", type: "Trappiste triple", origine: "Pays-Bas — Zundert", force: "8,2%", fa: "La trappiste du village de Van Gogh : dorée, épicée, rare." },
  { nom: "Grolsch", emoji: "🇳🇱", type: "Lager", origine: "Pays-Bas — Enschede", force: "5%", fa: "Le bouchon à levier « beugle » : le son du weekend néerlandais." },
  { nom: "Hertog Jan Dubbel", emoji: "🇳🇱", type: "Dubbel", origine: "Pays-Bas — Arcen", force: "7%", fa: "Le « duc Jean » brasse à Arcen : le Limbourg a du goût." },
  { nom: "De Molen Hel & Verdoemenis", emoji: "😈", type: "Stout impérial", origine: "Pays-Bas — Bodegraven", force: "11%", fa: "« Enfer et damnation » : un stout impérial taillé pour la cave." },
  { nom: "'t IJ Zatte", emoji: "🌬️", type: "Belgian-style strong ale", origine: "Pays-Bas — Amsterdam", force: "7,5%", fa: "Brassée sous un moulin à vent d'Amsterdam : la « saoule » du Zeeburg." },
  { nom: "Texels Skuumkoppe", emoji: "🐑", type: "Blonde", origine: "Pays-Bas — île de Texel", force: "5%", fa: "Brassée sur l'île des moutons : la mer est dans la mousse." },
  { nom: "Samichlaus", emoji: "🎅", type: "Doppelbock de Noël", origine: "Autriche — Vöslau", force: "14%", fa: "Brewed once a year le 6 décembre : « Père Noël » en suisse-allemand. La plus forte des lagers." },
  { nom: "Stift Engelszell Gregorius", emoji: "⛪", type: "Trappiste", origine: "Autriche — Engelhartszell", force: "9,7%", fa: "La trappiste de la vallée du Danube : la première d'Autriche." },
  { nom: "Stift Engelszell Benno", emoji: "⛪", type: "Trappiste", origine: "Autriche — Engelhartszell", force: "8%", fa: "La seconde trappiste d'Engelszell : fumée et froment au monastère." },
  { nom: "Ottakringer", emoji: "🇦🇹", type: "Lager", origine: "Autriche — Vienne", force: "5,5%", fa: "La bière des guinguettes viennoises : l'été à Ottakring s'appelle aussi festival." },
  { nom: "Stiegl", emoji: "🇦🇹", type: "Lager", origine: "Autriche — Salzbourg", force: "4,9%", fa: "La brasserie de Salzbourg depuis 1492 : Mozart buvait plus fort que ses opéras." },
  { nom: "Feldschlösschen", emoji: "🇨🇭", type: "Lager", origine: "Suisse — Rheinfelden", force: "5%", fa: "Brassée dans un château en forme de… château : le décor boit avec toi." },
  { nom: "Appenzeller Vollmond", emoji: "🌕", type: "Bières de pleine lune", origine: "Suisse — Appenzell", force: "5,2%", fa: "Brassée uniquement les nuits de pleine lune : la bière astronomique." },
  { nom: "Carlsberg", emoji: "🇩🇰", type: "Pilsner", origine: "Danemark — Copenhague", force: "3,8%", fa: "Le laboratoire Carlsberg a isolé la levure pure en 1883 : la science dans la bouteille." },
  { nom: "Tuborg", emoji: "🇩🇰", type: "Pilsner", origine: "Danemark — Copenhague", force: "4,6%", fa: "La bière du « J-day » danois : le jour où le pays boit sa première Tuborg de Noël." },
  { nom: "Mikkeller Beer Geek Breakfast", emoji: "🥣", type: "Stout au café", origine: "Danemark — Copenhague", force: "7,5%", fa: "Le petit-déjeuner des geeks : avoine et café en stout." },
  { nom: "Nøgne Ø India Pale Ale", emoji: "🇳🇴", type: "IPA", origine: "Norvège — Grimstad", force: "9%", fa: "« Île nue » : la brasserie du sud norvégien, l'amertume des fjords." },
  { nom: "Lammin Sahti", emoji: "🐟", type: "Sahti", origine: "Finlande — Lammi", force: "8%", fa: "Le sahti finlandais : filtré à travers des branches de genévrier, protégé par l'UE." },
  { nom: "Fix", emoji: "🇬🇷", type: "Lager", origine: "Grèce — Athènes", force: "4,7%", fa: "La bière duAthènes de 1864 : l'odeur du Pirée en bouteille." },
  { nom: "Mythos", emoji: "🇬🇷", type: "Lager", origine: "Grèce — Athènes", force: "4,7%", fa: "La mythologie se boit très fraîche, face à la mer Égée." },
  { nom: "Tipopils", emoji: "🇮🇹", type: "Pilsner artisanale", origine: "Italie — Lombardie", force: "5,2%", fa: "La pils de culte de Milan : le « Tipopils » est une religion locale." },
  { nom: "Baladin Nora", emoji: "🏺", type: "Bière aux épices égyptiennes", origine: "Italie — Piola", force: "6,8%", fa: "Recette inspirée des bières pharaoniques : safran et myrte dans le verre." },
  { nom: "Baladin Xyauyu", emoji: "🇮🇹", type: "Barleywine vieillie", origine: "Italie — Piola", force: "14%", fa: "Vieillie en fûts comme un vinaigre balsamique : l'orge de Modène." },
  { nom: "Del Borgo Re Ale", emoji: "🌶️", type: "Amber ale épicée", origine: "Italie — Borgorose", force: "6,5%", fa: "La nouvelle vague italienne : poivre de Timut et mousse crémeuse." },
  { nom: "Ichnusa", emoji: "🇮🇹", type: "Lager", origine: "Italie — Sardaigne", force: "4,7%", fa: "La bière de Sardaigne, au nom de la légende de la fée Ichnusa." },
  { nom: "Moretti", emoji: "🇮🇹", type: "Lager", origine: "Italie — Udine", force: "4,6%", fa: "Le moustachu de l'étiquette existe vraiment : un gentleman croisé en 1942." },
  { nom: "Menabrea", emoji: "🇮🇹", type: "Lager", origine: "Italie — Biella", force: "4,8%", fa: "La plus ancienne bière italienne (1846) : une blonde du Piémont très dignifiée." },
  { nom: "Estrella Damm", emoji: "🇪🇸", type: "Lager", origine: "Espagne — Barcelone", force: "4,6%", fa: "L'étoile de Barcelone depuis 1876 : la paella se boit aussi." },
  { nom: "Estrella Galicia", emoji: "🇪🇸", type: "Lager", origine: "Espagne — La Corogne", force: "5,5%", fa: "La bière de Galice : la route du pèlerinage a son étoile." },
  { nom: "Mahou Cinco Estrellas", emoji: "🇪🇸", type: "Lager", origine: "Espagne — Madrid", force: "5,1%", fa: "Les cinq étoiles de Madrid : après le Real, c'est la deuxième fierté locale." },
  { nom: "Alhambra Reserva 1925", emoji: "🕌", type: "Lager verte", origine: "Espagne — Grenade", force: "6,4%", fa: "La bouteille verte unique : la bière de l'Alhambra, à boire face à la Sierra." },
  { nom: "La Virgen", emoji: "🇪🇸", type: "Blonde artisanale", origine: "Espagne — Madrid", force: "4,7%", fa: "La « Vierge » de Madrid, brassée à la vue du Paseo : la chapelle du goût." },
  { nom: "Super Bock", emoji: "🇵🇹", type: "Lager", origine: "Portugal — Porto", force: "5,2%", fa: "La super du Nord : les amateurs de francesinha la réclament." },
  { nom: "Sagres", emoji: "🇵🇹", type: "Lager", origine: "Portugal — Almada", force: "4,9%", fa: "La bière de l'exposition de 1940 : le soleil du Portugal en canette." },
  { nom: "Żywiec", emoji: "🇵🇱", type: "Lager", origine: "Pologne — Żywiec", force: "5,6%", fa: "La bière des Tatras depuis 1856 : la montagne polonaise dans la pinte." },
  { nom: "Tyskie", emoji: "🇵🇱", type: "Lager", origine: "Pologne — Tychy", force: "5,2%", fa: "La bière des rois de Pologne, disent les buveurs de Tychy." },
  { nom: "Okocim", emoji: "🇵🇱", type: "Lager", origine: "Pologne — Brzesko", force: "5%", fa: "La brasserie de John II Sobieski… presque : Okocim brasse depuis 1845." },
  { nom: "Warka", emoji: "🇵🇱", type: "Lager", origine: "Pologne — Warka", force: "5,2%", fa: "La bière de Casimir le Grand disent les cracs : Warka est la doyenne." },
  { nom: "Żywiec Porter", emoji: "⚫", type: "Porter balte", origine: "Pologne — Żywiec", force: "9,5%", fa: "Le porter balte polonais : 9,5% de traditions houblonnées." },
  { nom: "Okocim Porter", emoji: "⚫", type: "Porter balte", origine: "Pologne — Brzesko", force: "8,3%", fa: "Le porter des bords de la Vistule : le froid polonais se boit noir." },
  { nom: "Grodziskie", emoji: "🌾", type: "Bière de froment fumé", origine: "Pologne — Grodzisk", force: "3%", fa: "Le « champagne polonais » : froment fumé, bulles fines, style ressuscité." },
  { nom: "Asahi Super Dry", emoji: "🇯🇵", type: "Dry lager", origine: "Japon — Tokyo", force: "5%", fa: "Le « karakuchi » : la dryness a conquis l'archipel en 1987." },
  { nom: "Sapporo", emoji: "🇯🇵", type: "Lager", origine: "Japon — Sapporo", force: "5%", fa: "La bière de la neige : l'étoile de Sapporo brille depuis 1876." },
  { nom: "Kirin Ichiban", emoji: "🇯🇵", type: "Lager", origine: "Japon — Tokyo", force: "5%", fa: "« Ichiban Shibori » : uniquement le premier pressage du moût, un luxe." },
  { nom: "Yebisu", emoji: "🇯🇵", type: "Lager premium", origine: "Japon — Tokyo", force: "5,5%", fa: "La grande soeur de la Sapporo : le conbini de haut standing." },
  { nom: "Hitachino Nest White Ale", emoji: "🍺", type: "Weizen japonaise", origine: "Japon — Ibaraki", force: "5,5%", fa: "Brassée dans une brasserie de sake : les levures ne parlent pas la même langue." },
  { nom: "Hitachino Red Rice", emoji: "🏮", type: "Rice ale", origine: "Japon — Ibaraki", force: "7%", fa: "Brassée avec du riz rouge fermenté : le sake s'invite dans la bière." },
  { nom: "Tsingtao", emoji: "🇨🇳", type: "Lager", origine: "Chine — Qingdao", force: "4,8%", fa: "Héritage de la colonie allemande de 1903 : la bière de Chine la plus exportée." },
  { nom: "Singha", emoji: "🇹🇭", type: "Lager", origine: "Thaïlande — Bangkok", force: "5%", fa: "Le lion de Thaïlande : la chaleur se boit fraîche, le lion ne dort jamais." },
  { nom: "Bia Hanoi", emoji: "🇻🇳", type: "Lager", origine: "Vietnam — Hanoï", force: "4,2%", fa: "La bière pression de Hanoï, bue sur des tabourets rouges au bord de la rue." },
  { nom: "Tiger", emoji: "🇸🇬", type: "Lager", origine: "Singapour", force: "5%", fa: "Le tigre de Singapour (1932) : la bière qui a traversé le détroit de Malacca." },
  { nom: "Corona", emoji: "🇲🇽", type: "Lager claire", origine: "Mexique — Ciudad de México", force: "4,5%", fa: "Le citron vert masque le goût du soleil : la plage vendue en bouteille transparente." },
  { nom: "Pacifico", emoji: "🌊", type: "Lager", origine: "Mexique — Mazatlán", force: "4,5%", fa: "La bière des surfeurs de Mazatlán : la vague se boit." },
  { nom: "Dos Equis XX", emoji: "🇲🇽", type: "Lager ambrée", origine: "Mexique — Monterrey", force: "4,8%", fa: "« The Most Interesting Man in the World » : la pub la plus drôle du monde." },
  { nom: "Modelo Negra", emoji: "🇲🇽", type: "Dunkel", origine: "Mexique — Mexico", force: "5,3%", fa: "La noire de Mexico : le mole de la bière, épices et caramel." },
  { nom: "Bohemia", emoji: "🇲🇽", type: "Pilsner", origine: "Mexique — Mexico", force: "5%", fa: "La « Concha de Plata » des bières mexicaines : la vieille dame de la brasserie." },
  { nom: "Quilmes", emoji: "🇦🇷", type: "Lager", origine: "Argentine — Quilmes", force: "4,8%", fa: "La bière du football argentin : le foot se boit en famille." },
  { nom: "Cusqueña", emoji: "🇵🇪", type: "Lager", origine: "Pérou — Cusco", force: "5%", fa: "La bière du Machu Picchu, à 3400 mètres d'altitude : la bière la plus haute du monde." },
  { nom: "Polar", emoji: "🇻🇪", type: "Lager", origine: "Venezuela — Caracas", force: "4,5%", fa: "L'ours polaire des Andes vénézuéliennes : la fraîcheur se boit en arepas." },
  { nom: "Unibroue La Fin du Monde", emoji: "🍁", type: "Triple", origine: "Canada — Chambly", force: "9%", fa: "« La fin du monde » : les explorateurs cherchaient l'Inde, ils ont trouvé le Québec." },
  { nom: "Unibroue Blanche de Chambly", emoji: "🍁", type: "Blanche", origine: "Canada — Chambly", force: "5%", fa: "La blanche du fort de Chambly : la Nouvelle-France se boit blanche." },
  { nom: "Unibroue Maudite", emoji: "🍁", type: "Strong amber", origine: "Canada — Chambly", force: "8%", fa: "La « damnée » : la légende du canot volant des voyageurs." },
  { nom: "Unibroue Trois Pistoles", emoji: "🍁", type: "Strong dark", origine: "Canada — Trois-Pistoles", force: "9%", fa: "Le cheval noir du village québécois : la légende se boit noire." },
  { nom: "Molson Canadian", emoji: "🍁", type: "Lager", origine: "Canada — Montréal", force: "5%", fa: "La plus vieille brasserie d'Amérique du Nord (1786) : le fleuve se boit." },
  { nom: "Coopers Sparkling Ale", emoji: "🇦🇺", type: "Ale", origine: "Australie — Adélaïde", force: "5,8%", fa: "Refermentée en bouteille : le dépôt de levure est un honneur, pas un défaut." },
  { nom: "Little Creatures Pale Ale", emoji: "🐬", type: "Pale ale", origine: "Australie — Fremantle", force: "5,4%", fa: "Née dans une ancienne usine de filets de crocodile : la crocodile de la pale ale." },
  { nom: "James Squire 150 Lashes", emoji: "🇦🇺", type: "Pale ale", origine: "Australie — Sydney", force: "4,2%", fa: "Le premier brasseur australien était un voleur déporté : il a eu « 150 coups de fouet »." },
  { nom: "Coopers Pale Ale", emoji: "🇦🇺", type: "Ale", origine: "Australie — Adélaïde", force: "4,5%", fa: "La boîte rouge de la barbie : refermentée, voilée, légendaire." },
  { nom: "Baltika 9", emoji: "🇷🇺", type: "Strong lager", origine: "Russie — Saint-Pétersbourg", force: "8%", fa: "La « devyatka » : la forte de Saint-Pétersbourg, à respecter l'hiver." },
  { nom: "Efes", emoji: "🇹🇷", type: "Lager", origine: "Turquie — Istanbul", force: "5%", fa: "La bière de Bosphore : le mezze se boit fraîche." },
  { nom: "Ursus", emoji: "🇷🇴", type: "Lager", origine: "Roumanie — Cluj", force: "5%", fa: "L'ours de Transylvanie : la bière veille sur les Carpates." },
  { nom: "Zlatorog", emoji: "🇸🇮", type: "Lager", origine: "Slovénie — Laško", force: "5%", fa: "Le bouquetin d'or des Alpes juliennes : la légende se boit fraîche." },
  { nom: "Zlatý Bažant", emoji: "🇸🇰", type: "Lager", origine: "Slovaquie — Hurbanovo", force: "5%", fa: "Le faisan d'or de la Slovaquie : le sud du pays a ses trésors." },
  { nom: "Dreher", emoji: "🇭🇺", type: "Lager", origine: "Hongrie — Budapest", force: "5%", fa: "Antal Dreher a inventé la lager viennoise à Budapest : la famille règne toujours." },
  { nom: "Obolon", emoji: "🇺🇦", type: "Lager", origine: "Ukraine — Kiev", force: "4,7%", fa: "La bière du Dniepr : le fleuve donne l'eau, Kiev donne la mousse." },
  { nom: "Castle Lager", emoji: "🇿🇦", type: "Lager", origine: "Afrique du Sud — Johannesburg", force: "5%", fa: "La bière du braai (le barbecue sud-africain) : le château du goût." },
  { nom: "Tusker", emoji: "🐘", type: "Lager", origine: "Kenya — Nairobi", force: "4,2%", fa: "L'éléphant du Kenya : la savane se boit très fraîche." },
  { nom: "Erdinger Dunkel", emoji: "🇩🇪", type: "Dunkelweizen", origine: "Allemagne — Erding", force: "5,6%", fa: "La dunkle du froment : le pain grillé à la bavaroise." },
  { nom: "Founders KBS", emoji: "🇺🇸", type: "Stout au café", origine: "États-Unis — Michigan", force: "12%", fa: "Breakfast Stout vieilli en fûts de bourbon : « Kentucky Breakfast », le matin des champions." },
  { nom: "Founders Breakfast Stout", emoji: "🥞", type: "Stout au café", origine: "États-Unis — Michigan", force: "8,3%", fa: "Café et chocolat double crème : le petit-déjeuner officiel du Michigan." },
  { nom: "Great Lakes Edmund Fitzgerald", emoji: "⚓", type: "Porter", origine: "États-Unis — Cleveland", force: "6%", fa: "Nommée d'après le cargo qui a coulé dans le lac Érié : le porter des marins." },
  { nom: "Löwenbräu", emoji: "🍺", type: "Helles", origine: "Allemagne — Munich", force: "5,2%", fa: "Le lion brune de Munich : à l'Oktoberfest, le lion rugit dans les litre." },
  { nom: "Hacker-Pschorr", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "4,9%", fa: "Le « ami du peuple » : la brasserie des révolutions munichoises." },
  { nom: "Spaten", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "4,9%", fa: "Le « pie » de la brasserie : la première à faire de la publicité (1499... non, 1894)." },
  { nom: "Harvey's Tom Paine", emoji: "🇬🇧", type: "Old ale", origine: "Angleterre — Lewes", force: "6,5%", fa: "Nommée d'après le révolutionnaire de Lewes : la bière des droits de l'homme." },
  { nom: "Hoegaarden Grand Cru", emoji: "🇧🇪", type: "Blanche forte", origine: "Belgique — Hoegaarden", force: "8,5%", fa: "La blanche dopée au coriandre et au curaçao : la grande réserve du froment." },
  { nom: "St Bernardus Tripel", emoji: "🇧🇪", type: "Triple d'abbaye", origine: "Belgique — Watou", force: "8%", fa: "La triple du phénix de Watou : ronde, épicée, mousse de soie." },
  { nom: "Weihenstephaner Pils", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Freising", force: "5%", fa: "La pils des moines bavarois : quand l'ordre cistercien rencontre le houblon de Hallertau." },
  { nom: "Orval Grande Réserve", emoji: "🐟", type: "Trappiste vieillie", origine: "Belgique — Orval", force: "6,4%", fa: "L'Orval mise en réserve : les bouteilles numérotées partent en un clin d'œil." },
  { nom: "Cantillon Vigneronne", emoji: "🍇", type: "Lambic aux raisins", origine: "Belgique — Bruxelles", force: "5%", fa: "Des raisins muscat sur lambic : la brasserie rend hommage au vin, en silence." },
  { nom: "Grimbergen Rouge", emoji: "🇧🇪", type: "Bière fruitée ambrée", origine: "Belgique — Grimbergen", force: "6%", fa: "Le phénix se pare de rouge : des arômes de fruits rouges et de caramel." },
  { nom: "Samuel Smith Nut Brown Ale", emoji: "🌰", type: "Brown ale", origine: "Angleterre — Tadcaster", force: "5%", fa: "La brown aux noisettes du Yorkshire : douce comme un pub au coin du feu." },
];

const BIERES_CULTES_EN = {
  "Westvleteren 12": "Brewed by label-shy monks: to buy it, book an appointment at the abbey itself.",
  "Westvleteren Blond": "The monks' small blond, sold only at the monastery gate.",
  "Westvleteren 8": "One of the three Westvleteren, every bit as rare as its sisters.",
  "Orval": "Legend says a trout returned a lost ring to the abbey fountain — that's her on the label.",
  "Petit Orval": "The small Orval, served only at the abbey's inn: the monks keep it for passing pilgrims.",
  "Rochefort 6": "The most discreet of the three Rochefort, a connoisseur favorite.",
  "Rochefort 8": "The perfect balance between the 6 and the 10, say the monks.",
  "Rochefort 10": "The numbers come from pre-war wort densities. Sip the 10 like a whisky.",
  "Rochefort Triple Extra": "The monks' limited edition: when it's there, grab it.",
  "Chimay Bleue": "The Grande Réserve: strong, spiced, built for cellar aging.",
  "Chimay Rouge": "The first Chimay in history, gentle and fruity.",
  "Chimay Blanche": "The 'Cinq Cents': crisp bitterness with a muscat finish.",
  "Chimay Dorée": "For decades it was reserved for the monks and their guests.",
  "Westmalle Tripel": "THE reference tripel: the whole world tries to copy it.",
  "Westmalle Dubbel": "The mother dubbel: it set the style for all abbey browns.",
  "Westmalle Extra": "The monks' own table beer, impossible to find in shops.",
  "Achel Blond": "Brewed near the Dutch border in the most discreet Trappist abbey.",
  "Achel Bruin": "A keeping brown with a light touch of toasted caramel.",
  "Leffe Blonde": "Born at Leffe abbey in 1152: monks brewed to fund the upkeep.",
  "Leffe Brune": "Soft and roasted, the Sunday-afternoon brown.",
  "Leffe Rituel 9°": "A Leffe that climbs: sip it slowly, no gulping.",
  "Grimbergen Blonde": "The phoenix on the label: the abbey burned down and was rebuilt many times.",
  "Grimbergen Optimo Bruno": "Grimbergen's 'beer of the scholars', a barrel of excellence.",
  "Maredsous 8": "The Benedictine abbey's brown, perfect with its namesake cheese.",
  "Maredsous 10": "The full-bodied one of the family — to share... or not.",
  "St Bernardus Abt 12": "Once brewed for the Westvleteren monks: the secular cousin of the 12.",
  "St Bernardus Wit": "A creamy traditional-style wit, lemon optional.",
  "St Bernardus Christmas Ale": "The Flemish Advent beer: spices, dates and a good fireplace.",
  "St Bernardus Grottenbier": "Designed to age in the region's marble caves.",
  "Affligem Blonde": "A thousand-year-old abbey beer with cappuccino-grade foam.",
  "Affligem Tripel": "A high-flying tripel inherited from the Affligem monks.",
  "Val-Dieu Triple": "The Val-Dieu abbey reopened its brewery in the year 2000.",
  "Val-Dieu Brune": "A keeping brown brewed with the abbey spring water.",
  "Tongerlo Tripel": "A tripel from the country's oldest canons' abbey.",
  "Floreffe Blonde": "The Floreffe canons were already brewing in the 12th century.",
  "Postel Blond": "The round taste of the monks of the Postel forest.",
  "Bornem Double": "A brown in the style of the old Lent fast beers.",
  "Ename Dubbel": "A brown from the vanished Ename abbey, resurrected by brewery.",
  "Saint-Feuillien Brune": "The Saint-Feuillien abbey has brewed in Hainaut since 1873.",
  "Steenbrugge Dubbel": "A brown from Saint-Peter's abbey in Steenbrugge, monks' recipe.",
  "Duvel": "A brewer tasted the first batch and shouted 'a real Duvel!' — a real devil.",
  "Duvel Tripel Hop": "Three fresh hops instead of one: the pentathlon version of the Devil.",
  "Chouffe": "The white-bearded gnome protects the brewery — and steals beers from tourists.",
  "La Chouffe Mc Chouffe": "A scotch ale brewed by Belgians with a Scottish gnome on the label.",
  "N'Ice Chouffe": "The winter Chouffe: spices and damsons, plus the gnome's beanie.",
  "Delirium Tremens": "The pink elephant on the bottle: here the delirium is in the name.",
  "Delirium Noël": "The festive version of the delirium: drink before seeing pink reindeer.",
  "Piraat": "10.5% of hearty hops: the jolly roger of Belgian beers.",
  "Gulden Draak": "The golden dragon: a third fermentation in the bottle, a keeping monster.",
  "Kasteel Rouge": "A brown steeped with cherries: the dessert you drink.",
  "Kasteel Donker": "The Ingelmunster castle brown, sweet as barley syrup.",
  "Ciney Blonde": "The Ciney blond with generous foam and polite bitterness.",
  "Ciney Brune": "The Condroz brown, caramel and barley cream.",
  "Brigand": "Named after the 1798 rebels: it runs its own rebellion.",
  "Lucifer": "The name says it all: golden, devilishly spiced, damnation guaranteed.",
  "Judas": "A kiss and a slap: sweetness first, alcohol after.",
  "Gouden Carolus Classic": "Emperor Charles Quint's beer, say the Mechelen brewers.",
  "Gouden Carolus Hopsinjoor": "Nine different hops: the crown is worn on the tongue too.",
  "Bush Ambrée": "The strongest of the classic Belgian beers: respect it, don't taunt it.",
  "Barbar": "A blond brewed with acacia honey: the bee does half the work.",
  "Verboden Vrucht": "The forbidden fruit: Adam and Eve on the label, the sin in the glass.",
  "Cuvée des Trolls": "Brewed with dried oranges: full mouth, light head.",
  "Satan Gold": "A 'beer of the gods': the marketing was already strong in 1988.",
  "Tripel Karmeliet": "Barley, wheat AND oats: the three-grain tripel, a crisp delight.",
  "Straffe Hendrik": "The 'strong Henri' of the Van Houcke family, in medieval Bruges.",
  "Brugse Zot Dubbel": "The 'fools of Bruges' mocked by Emperor Maximilian: the nickname stuck.",
  "Kwak": "The coachman's stirrup-cup glass hooks onto the bench. Strap yourself in.",
  "Poperings Hommelbier": "Hommel means hops in Flemish: you drink the hop capital of Belgium.",
  "Hommel Ale": "Brewed by the Van Eecke family, the other hop farm of the area.",
  "Lupulus": "Brewed with Ardennes spring water: hops rule here.",
  "Silly Saison": "The Hainaut farm saison, as told by the Silly brewery.",
  "Saison Dupont": "The world's reference saison, born to refresh the harvest crews.",
  "Avec les Bons Vœux": "Dupont's premium saison: the greetings card you drink.",
  "La Merveille": "A saison from the Blaugies farm brewery, by the hedgerows.",
  "Fantôme": "Dany Prignon brews unpredictable saisons: every cask is a surprise.",
  "Taras Boulba": "Nabokov on the label, fresh hops in the glass: 4.5% of poetry.",
  "Zinnebir": "The river Senne lends its name to this crisp amber.",
  "XX Bitter": "De Ranke made it for bitterness fanatics: harsh and proud.",
  "Guldenberg": "De Ranke's other gem: soft, golden, hoppy the old way.",
  "De Ranke Kriek": "Real cherries on lambic, no syrup: honest tartness.",
  "Wipers Times": "A tribute to the Great War trench newspaper, brewed English-style.",
  "Troubadour Mocha Stout": "A stout the Belgian way: cocoa and coffee, still packing heat.",
  "Bourgogne des Flandres": "A blend of lambic and sweet brown: Burgundy wine, beer version.",
  "Rodenbach": "Aged two years in oak: acidity and cherry, the Flanders signature.",
  "Rodenbach Vintage": "Single cask, vintage-dated: the grand cru of Flemish reds.",
  "Duchesse de Bourgogne": "Aged 18 months in oak: the duchess graces fine tables.",
  "Liefmans Goudenband": "So thick it was traditionally cut open with a knife.",
  "Liefmans Cuvée Brut": "Cherries steeped champagne-style: bubbles included.",
  "Cantillon Gueuze": "Fermented by the wild airborne yeasts of Brussels, in an open attic.",
  "Cantillon Kriek": "Two hundred grams of cherries per liter: fruit and acidity in a duel.",
  "Cantillon Rosé de Gambrinus": "Noble raspberry on one-year lambic: pink and biting.",
  "Cantillon Fou' Foune": "Roussillon apricots on lambic: the brewer's electric fairy.",
  "3 Fonteinen Oude Geuze": "A blend of one-, two- and three-year lambics, corked like champagne.",
  "3 Fontainen Schaarbeekse Kriek": "Brussels' small sour cherries, just like the old days.",
  "Boon Oude Geuze Mariage Parfait": "The 'perfect marriage': three years in the barrel before bottling.",
  "Boon Kriek": "The sweet-sour kriek of the Lembeek brewery-museum.",
  "Lindemans Gueuze": "The filtered, sweetened gueuze: the gateway to the lambic world.",
  "Lindemans Kriek": "The approachable kriek: perfect for converting skeptics.",
  "Lindemans Framboise": "Raspberry syrup or not, it still rests on real lambic.",
  "Mort Subite Oude Gueuze": "'Sudden death': the name of the Brussels café where it was drunk.",
  "Belle-Vue Gueuze": "The Sunday gueuze: soft, lemony, with fine foam.",
  "Oud Beersel Oude Geuze": "Counter-style gueuze, straight from the Flemish schoolbook.",
  "Tilquin Gueuze": "The last independent gueuze blender: he buys the lambic, not the brewery.",
  "Hanssens Oude Gueuze": "One of the sourest in the country: teeth tingle, hearts flutter.",
  "Girardin Gueuze": "The giraffe on the label: a rustic Walloon Brabant gueuze.",
  "De Cam Oude Geuze": "Blended at the farm, on the high plateaus of the Pajottenland.",
  "Hoegaarden": "The wit with coriander and orange peel: invented by Pierre Celis.",
  "Blanche de Namur": "Born from the legend of the 'Blonde of Namur', a 15th-century princess.",
  "Brugs Tarwebier": "The Bruges wheat beer: refreshing after the Minnewater.",
  "Weihenstephaner": "The world's oldest working brewery (1040): it survived everything.",
  "Weihenstephaner Vitus": "A wheat doppelbock: banana and clove, supercharged.",
  "Schneider Weisse Tap 6": "Georg Schneider has kept Munich wheat alive since 1872.",
  "Aventinus": "Bavaria's oldest wheat doppelbock: complex and velvety.",
  "Schneider Edel Weisse": "The tonic, spicy version of the Schneider wheat.",
  "Erdinger Weissbier": "The 'champion's' weissbier: sport and beer, contract signed.",
  "Franziskaner": "The Franciscan monk on the label: central Munich's wheat beer.",
  "Maisel Weisse": "Bayreuth's 'Weisse pearl': fruity, fleshy, generous.",
  "Ayinger Bräu Weisse": "Brewed in the village of Aying: the foam is actual cream.",
  "Schöfferhofer Weizen": "The Mainz wheat beer you find everywhere and always re-order.",
  "Augustiner Helles": "Munich's favorite: gravity-poured straight from the tap.",
  "Augustiner Edelstoff": "'Noble stuff': the Augustinian brewery's treasure, bottles only.",
  "Augustiner Dunkel": "The Munich brown par excellence: toasted bread and caramel.",
  "Tegernseer Spezial": "The former Tegernsee abbey brewery: the lake, the hills, the beer.",
  "Jever Pils": "The north's 'pils with bite': dry, herbal, sharp as a sea breeze.",
  "Warsteiner": "The 'queen of pils' according to the ads: Germany's everywhere-bomb.",
  "Radeberger": "East Germans' favorite pils, born under Bismarck.",
  "Bitburger": "'Bitte ein Bit': Germany's most quotable slogan.",
  "Veltins": "The Sauerland pils, always served ice cold.",
  "Flensburger": "The swing-top 'plop': you hear it before you drink it.",
  "Rothaus Tannenzäpfle": "The 'little pine cone' from the Black Forest, land of fir trees.",
  "Kneitinger Pils": "The Regensburg pils, Bavarian purists' favorite.",
  "Hofbräu Original": "The Duke of Bavaria's brewery: served in one-liter mugs.",
  "Löwenbräu Original": "The Munich lion has brewed since 1383: the Oktoberfest beer.",
  "Paulaner Münchner Hell": "The Paulaner monks brewed to survive: their hell is holy.",
  "Paulaner Salvator": "The 'Savior': monks fasted on it, hence the name. Holy excuse.",
  "Ayinger Celebrator": "The goat medal on the label: the reference doppelbock.",
  "Andechser Doppelbock": "Brewed by Benedictines on the Andechs hill: a tasty pilgrimage.",
  "Korbinian": "Named after Saint Korbinian, the bishop with the bear: legend in a bottle.",
  "König Ludwig Weiss": "The royal brewery by Hohenschwangau, facing Louis II's castle.",
  "EKU 28": "Once the strongest beer in the world: sipped like a digestif.",
  "Kulmbacher Eisbock": "The legend: a cask left outside froze, ice removed, alcohol concentrated.",
  "Schneider Aventinus Eisbock": "Aventinus partially frozen: banana, chocolate and dark fruit.",
  "Einbecker Mai-Ur-Bock": "Einbeck is the mother of bocks: its name gave 'Bock' to Bavaria.",
  "Schlenkerla Märzen": "Beechwood-smoked malt: the ham of beers, Bamberg loves it.",
  "Schlenkerla Weizen": "A smoked wheat: bakery and bar counter in one glass.",
  "Spezial Rauchbier": "Bamberg's other smoke, gentler: the town counts two schools.",
  "Diebels Alt": "The 'thief': the reference alt, red-brown and dry.",
  "Uerige Alt": "The 'deliciously sour' Uerige alt: tiny glasses at the counter.",
  "Schumacher Alt": "The oldest alt house (1838): you drink standing, packed, happy.",
  "Füchschen Alt": "The little fox of old Düsseldorf: bitter and rustic.",
  "Gaffel Kölsch": "The reference thistle-glass kölsch: while the glass is full, they refill.",
  "Reissdorf Kölsch": "Cologne's most-drunk kölsch: 20cl at a time, sweet madness.",
  "Früh Kölsch": "The kölsch by the old harbor next to the cathedral: a pilgrimage.",
  "Mühlen Kölsch": "Brewed at the city mill: the most confidential kölsch.",
  "Berliner Kindl Weisse": "The Prussian kings' beer, so sour it takes a shot of syrup.",
  "Pinkus Alt": "The organic brewery before its time: real taste since 1816.",
  "Weltenburger Barock Dunkel": "The abbey claims the world's oldest monastery brewery title.",
  "Altbairisch Dunkel": "Old Bavaria's brown: rye bread, prune, softness.",
  "Köstritzer Schwarzbier": "Goethe's black beer: the poet sipped this 'black velvet' while writing.",
  "Goslarer Gose": "Sour, salty, coriander-spiced: forgotten by the Middle Ages, then revived.",
  "Kuchlbauer Weisse": "Its golden tower was designed by Hundertwasser: art with your weissbier.",
  "Neumarkter Lammsbräu": "Germany's organic pioneer: the beer of respect, since 1979.",
  "Beck's": "The green bottle only leaves Bremen for export: locals drink it on draft.",
  "St. Georgen Bräu Kellerbier": "Brewed 'on the lees' in the shade of the cellars: perfect cellar beer.",
  "Fischer Tradition": "The keeping beer: brewed in winter, aged for months to last the summer.",
  "Adelscott": "Peat-smoked malt, whisky-style: Alsace doing Scotland.",
  "Pelforth Blonde": "'Pel my god': the Pelforth pelican conquered French bistro counters.",
  "Pelforth Brune": "The 60s brown: fathers still ask for it at the counter.",
  "3 Monts": "The North's keeper: brewed in the Flemish heights, built to age.",
  "La Goudale": "Conceived to pay off 'goudale' debts: the counts of Flanders' beer.",
  "Jenlain Ambrée": "The Northern beer that relaunched French brewing in 1974.",
  "La Choulette Ambrée": "Brewed in a former Northern farmhouse brewery: the return of taste.",
  "Ch'ti Blonde": "The Ch'ti in beer form: welcome to the North's bistro.",
  "Ch'ti Rousse": "The miners' red: coal in the glass, but nicer.",
  "Mont des Cats": "France's only Trappist: once brewed at the abbey, revived in 2016.",
  "Bière du Démon": "12% alcohol: the French demon — respect it before whistling at it.",
  "Cervoise Lancelot": "The Gauls' cervoise, brewed in a Breton castle's hearth.",
  "Telenn Du": "Breton buckwheat: the crêpe you can drink.",
  "Britt Blonde": "The Breton's apéritif: Armorican wheat.",
  "Britt Rousse": "The Breton red: caramel and demi-sel butter (almost).",
  "Meteor Pils": "Alsace's independent: the last big family brewery.",
  "Meteor Blanc de Blancs": "An Alsatian wheat wit: the crown of the Vosges valleys.",
  "Ninkasi IPA": "Born in Lyon, city of Ninkasi the Sumerian goddess of beer.",
  "Deck & Donohue East Indie Pale Ale": "Two Americans in Paris: the capital's honest IPA.",
  "La Goutte d'Or": "Brewed in the Goutte d'Or district, like the wine once named after it.",
  "Bière du Mont Blanc — La Blonde": "Brewed with Alpine water: less mint, more foam.",
  "Bière du Mont Blanc — La Rousse": "The Alpine red: snowmelt water in a bottle.",
  "Mistral Gagnal": "The mistral in the sails and the counter: Marseille brews.",
  "Anosteké Blonde": "The Northern festivals' refrain: 'Anosteké!' as the Ch'tis say.",
  "Pietra": "Brewed with Corsican chestnut flour: the maquis in a glass.",
  "Colomba": "The Corsican Easter wit, with orange blossom.",
  "Guinness": "Arthur Guinness signed a 9,000-year lease. His father left him 100 pounds — he put them into beer.",
  "Guinness Foreign Extra": "The strong version once exported to the tropics: the one that won West Africa.",
  "Murphy's": "Guinness' gentle Cork rival: less bitter, creamier.",
  "Beamish": "The third musketeer of Irish stouts, loyal to Cork.",
  "Smithwick's": "Kilkenny's monastery red, Ireland's oldest brewery.",
  "O'Hara's Irish Stout": "The Carlow crafters' stout: Ireland's real-taste revival.",
  "Fuller's London Pride": "London's pride since 1959: bitterness as a politeness.",
  "Fuller's ESB": "The 'Extra Special Bitter' par excellence: a many-times champion.",
  "Fuller's London Porter": "The London docklands style, revived at Chiswick: black, soft, deep.",
  "Fuller's Vintage Ale": "Vintage-dated each year: cellared like a fine Bordeaux.",
  "Fuller's 1845": "Brewed for the brewery's anniversary: the red-wax bottle.",
  "Samuel Smith Oatmeal Stout": "Oats in the stout: velvet texture, brewing since 1758.",
  "Samuel Smith Taddy Porter": "The Yorkshire miners' porter: black and nourishing.",
  "Samuel Smith Old Brewery Pale": "Still brewed in Yorkshire stone squares: tradition bottled.",
  "Theakston Old Peculier": "'Peculier' is a church-law word: a prune-flavored old ale.",
  "Robinson's Old Tom": "Several times voted world's best beer: the label cat has good taste.",
  "Young's Double Chocolate Stout": "Dark chocolate and vanilla in a stout: the English dessert.",
  "Hook Norton Old Hooky": "Brewed with an 1899 steam engine: the village pours at the pump.",
  "Timothy Taylor Landlord": "English drinkers' favorite: it even converted Hollywood.",
  "St Austell Tribute": "Brewed for the 1999 solar eclipse: Cornwall in a cask.",
  "Wadworth 6X": "Deliveries are still made by horse-drawn dray in Devizes: the drayman's 6X.",
  "Shepherd Neame Spitfire": "Born for the Battle of Britain's 50th anniversary: humor in a bottle.",
  "Bishop's Finger": "The bishop's finger really does point the way to the brewery.",
  "Harvey's Sussex Best": "The Sussex bitter, served at the perfect cellar temperature.",
  "Adnams Southwold": "The Suffolk coast beer: the seagulls demand some too.",
  "Hobgoblin": "Wychwood's goblin: the red that conquered English students.",
  "Bombardier": "'English Premium Bitter': the beer you drink like an anthem.",
  "Black Sheep Riggwelter": "'Riggwelter' is Yorkshire for a sheep on its back. You get it after the pint.",
  "Innis & Gunn Original": "Aged in ex-whisky casks: all of Scotland in one bottle.",
  "Traquair House Ale": "Brewed in Scotland's oldest inhabited house, since 1965.",
  "Fraoch": "Brewed with heather: the Picts' recipe, revived by the Williams brothers.",
  "BrewDog Punk IPA": "The punk that unbuttoned Britain: bitterness as a manifesto.",
  "Thornbridge Jaipur": "The new-wave English IPA: floral, dry, many times medaled.",
  "Meantime London Pale Ale": "Greenwich's pale ale: the meridian of British bitterness.",
  "Bass Pale Ale": "The red triangle: the UK's first registered trademark (1876).",
  "Harviestoun Bitter & Twisted": "Citrus and dry bitterness: the name's twist is in the glass.",
  "Newcastle Brown Ale": "The docks' 'Nukey Brown': Northern workers' foam.",
  "Boddingtons": "'The cream of Manchester': nitro gives a lush texture.",
  "Tetley's": "The Yorkshire pudding drinks too: Leeds' very creamy bitter.",
  "Sierra Nevada Pale Ale": "The one that launched America's craft revolution in 1980.",
  "Sierra Nevada Torpedo": "The 'Torpedo': invented to dry-hop in a continuous stream.",
  "Goose Island IPA": "Chicago's IPA, bought by AB InBev: purists wince, it stays good.",
  "Goose Island Bourbon County": "Whiskey-barrel aged: every Black Friday the queues grow.",
  "Sam Adams Boston Lager": "The one that proved Americans beer could have taste.",
  "Sam Adams Utopias": "28% alcohol, undistilled: banned in some states. Collectors' darling.",
  "Brooklyn Lager": "The comeback lager: New York got its beer back in 1988.",
  "Lagunitas IPA": "Brewed by Petaluma's rascals: insolence with a hop kick.",
  "Lagunitas A Little Sumpin' Sumpin'": "'A little something': hops and wheat, the Californian cocktail.",
  "Stone IPA": "'Proud. Arrogant. Not for everyone.': the gargoyle in a bottle.",
  "Ballast Point Sculpin": "San Diego's sculpin fish: the IPA that put the city on the map.",
  "Russian River Pliny the Elder": "The brewery queues are legendary: the reference double IPA.",
  "Dogfish Head 60 Minute": "Hopped continuously for 60 minutes: the scholars' IPA.",
  "Dogfish Head 120 Minute": "18% and still standing: the monster to sip like port.",
  "Bell's Two Hearted": "Hemingway's trout river: contest judges' perfect IPA.",
  "New Belgium Fat Tire": "Named after the founder's bike ride in France: America's nicest amber.",
  "Anchor Steam": "Steam-fermented on San Francisco rooftops since 1896.",
  "The Alchemist Heady Topper": "Sold only at the brewery, in cans: the hop pilgrims' grail.",
  "Boulevard Tank 7": "America's saison: born from a cask 'gone wrong' that became a cult.",
  "Victory Prima Pils": "America's honest pils: dry, floral, true to old Europe.",
  "New Glarus Spotted Cow": "Unfindable outside Wisconsin: the Midwest's best-kept secret.",
  "Left Hand Milk Stout": "Lactose softens the black: milk texture, night color.",
  "Oskar Blues Dale's Pale Ale": "The first craft in a can (2002): 'canned beer is good', they said.",
  "Pabst Blue Ribbon": "Blue ribbon won in 1893, dusted off by hipsters.",
  "Blue Moon": "The Rockies' wit, with its mandatory orange wheel.",
  "Deschutes Fresh Squeezed": "Squeezed the day, as its name says: Oregon in citrus.",
  "Pilsner Urquell": "The very first pilsner (1842). Every lager on Earth descends from it.",
  "Budweiser Budvar": "The 'real' Czech Budweiser: the lawsuit with the American one runs since 1907.",
  "Budvar Dark": "Budvar's black one: malt caramel, softness, great craft.",
  "Kozel": "The billy goat on the label, guardian of the brewing village.",
  "Kozel Černý": "The goat's black one: light, coffee, drank by the Czech pint.",
  "Staropramen": "Prague's pub beer: the Smíchov 'great toast'.",
  "Bernard": "Brewed with Bohemian-Moravian spring water: unfiltered in the 'Family' version.",
  "Krušovice": "The Bohemian kings' beer, served at court since the 16th century.",
  "U Fleků": "Brewed on the spot in Prague since 1499: the city's oldest taproom.",
  "Primátor": "The Náchod fortress beer: guardians of taste.",
  "Heineken": "The 'star' foam: the brewer's A-yeast invention deserves a glass.",
  "La Trappe Quadrupel": "The mother quadrupel: born at Koningshoeven, strong as the monks' faith.",
  "La Trappe Dubbel": "The Dutch monks' dubbel: the country's only Trappist monastery.",
  "La Trappe Bockbier": "The monks' bock: brewed once a year, autumn in a bottle.",
  "Zundert": "Van Gogh's village Trappist: golden, spiced, rare.",
  "Grolsch": "The swing-top 'beugel' cap: the sound of the Dutch weekend.",
  "Hertog Jan Dubbel": "'Duke John' brews in Arcen: Limburg has taste.",
  "De Molen Hel & Verdoemenis": "'Hell and damnation': an imperial stout built for the cellar.",
  "'t IJ Zatte": "Brewed under an Amsterdam windmill: the Zeeburg 'drunk one'.",
  "Texels Skuumkoppe": "Brewed on the island of sheep: the sea is in the foam.",
  "Samichlaus": "Brewed once a year on December 6: 'Santa Claus' in Swiss-German. The strongest of lagers.",
  "Stift Engelszell Gregorius": "The Danube valley's Trappist: Austria's first.",
  "Stift Engelszell Benno": "Engelszell's second Trappist: smoke and wheat at the monastery.",
  "Ottakringer": "Vienna's wine-tavern beer: summer in Ottakring is also a festival.",
  "Stiegl": "Salzburg's brewery since 1492: Mozart drank stronger than his operas.",
  "Feldschlösschen": "Brewed in a castle shaped like... a castle: the scenery drinks with you.",
  "Appenzeller Vollmond": "Brewed only on full-moon nights: the astronomical beer.",
  "Carlsberg": "The Carlsberg lab isolated pure yeast in 1883: science in the bottle.",
  "Tuborg": "The Danish 'J-day' beer: the day the country drinks its first Christmas Tuborg.",
  "Mikkeller Beer Geek Breakfast": "The geeks' breakfast: oats and coffee in a stout.",
  "Nøgne Ø India Pale Ale": "'Naked island': Norway's southern brewery, fjord bitterness.",
  "Lammin Sahti": "The Finnish sahti: filtered through juniper branches, EU-protected.",
  "Fix": "Athens' beer of 1864: the smell of Piraeus in a bottle.",
  "Mythos": "Greek mythology drinks ice cold, facing the Aegean Sea.",
  "Tipopils": "Milan's cult pils: 'Tipopils' is a local religion.",
  "Baladin Nora": "A recipe inspired by pharaonic beers: saffron and myrtle in the glass.",
  "Baladin Xyauyu": "Cask-aged like balsamic vinegar: Modena's barley wine.",
  "Del Borgo Re Ale": "The Italian new wave: Timut pepper and creamy foam.",
  "Ichnusa": "Sardinia's beer, named after the Ichnusa fairy legend.",
  "Moretti": "The label's mustached gentleman really existed: a gentleman met in 1942.",
  "Menabrea": "Italy's oldest beer (1846): a very dignified Piedmont blond.",
  "Estrella Damm": "Barcelona's star since 1876: paella pairs well with it.",
  "Estrella Galicia": "Galicia's beer: the pilgrimage route has its own star.",
  "Mahou Cinco Estrellas": "Madrid's five stars: after the Real, the city's second pride.",
  "Alhambra Reserva 1925": "The unique green bottle: Granada's beer, sipped facing the Sierra.",
  "La Virgen": "Madrid's craft blond, brewed in sight of the Paseo: the chapel of taste.",
  "Super Bock": "The North's super: francesinha eaters demand it.",
  "Sagres": "The 1940 exhibition's beer: Portuguese sun in a can.",
  "Żywiec": "The Tatra mountains' beer since 1856: Polish highlands in a pint.",
  "Tyskie": "The Polish kings' beer, say the drinkers of Tychy.",
  "Okocim": "The brewery of John III Sobieski... almost: Okocim has brewed since 1845.",
  "Warka": "Casimir the Great's beer, say the experts: Warka is the doyenne.",
  "Żywiec Porter": "The Polish Baltic porter: 9.5% of hoppy tradition.",
  "Okocim Porter": "The Vistula banks' Baltic porter: the Polish cold drinks black.",
  "Grodziskie": "The 'Polish champagne': smoked wheat, fine bubbles, a revived style.",
  "Asahi Super Dry": "The 'karakuchi': dryness conquered the archipelago in 1987.",
  "Sapporo": "The snow city's beer: Sapporo's star has shone since 1876.",
  "Kirin Ichiban": "'Ichiban Shibori': only the wort's first pressing, a luxury.",
  "Yebisu": "Sapporo's big sister: the premium convenience-store beer.",
  "Hitachino Nest White Ale": "Brewed in a sake brewery: the yeasts speak different languages.",
  "Hitachino Red Rice": "Brewed with fermented red rice: sake crashes the beer party.",
  "Tsingtao": "Legacy of the 1903 German colony: China's most exported beer.",
  "Singha": "Thailand's lion: heat is drunk cold, the lion never sleeps.",
  "Bia Hanoi": "Hanoi's draft beer, sipped on red stools by the roadside.",
  "Tiger": "Singapore's tiger (1932): the beer that crossed the Malacca Strait.",
  "Corona": "Lime masks the taste of sunshine: the beach sold in a clear bottle.",
  "Pacifico": "Mazatlán's surfers' beer: the wave you can drink.",
  "Dos Equis XX": "'The Most Interesting Man in the World': the funniest ad ever.",
  "Modelo Negra": "Mexico City's black one: the beer version of mole, spice and caramel.",
  "Bohemia": "The Mexican beers' 'Silver Conch': the brewery's old lady.",
  "Quilmes": "Argentina's football beer: the game is watched with family and Quilmes.",
  "Cusqueña": "Machu Picchu's beer at 3,400 m: the highest brewery beer in the world.",
  "Polar": "The Andes' polar bear: Venezuelan freshness goes with arepas.",
  "Unibroue La Fin du Monde": "'The end of the world': explorers sought India, they found Québec.",
  "Unibroue Blanche de Chambly": "The Chambly fort's wit: New France drinks white.",
  "Unibroue Maudite": "The 'damned one': the flying canoe legend of the voyageurs.",
  "Unibroue Trois Pistoles": "The Québec village's black horse: the legend drinks black.",
  "Molson Canadian": "North America's oldest brewery (1786): the river drinks too.",
  "Coopers Sparkling Ale": "Bottle-conditioned: the yeast sediment is an honor, not a flaw.",
  "Little Creatures Pale Ale": "Born in a former crocodile-filet factory: the crocodile of pale ales.",
  "James Squire 150 Lashes": "Australia's first brewer was a deported thief: he got '150 lashes'.",
  "Coopers Pale Ale": "The barbie's red tin: bottle-conditioned, cloudy, legendary.",
  "Baltika 9": "The 'devyatka': St Petersburg's strong one, respect it in winter.",
  "Efes": "The Bosphorus beer: meze is drunk cold.",
  "Ursus": "The Transylvanian bear: the beer watches over the Carpathians.",
  "Zlatorog": "The Julian Alps' golden ibex: the legend drinks cold.",
  "Zlatý Bažant": "Slovakia's golden pheasant: the south of the country has treasures.",
  "Dreher": "Antal Dreher invented Vienna lager in Budapest: the family still reigns.",
  "Obolon": "The Dnieper's beer: the river gives the water, Kyiv gives the foam.",
  "Castle Lager": "The braai's beer (South African barbecue): the castle of taste.",
  "Tusker": "Kenya's elephant: the savanna drinks very cold.",
  "Erdinger Dunkel": "The wheat dark: Bavarian toasted bread.",
  "Founders KBS": "Breakfast Stout aged in bourbon barrels: 'Kentucky Breakfast', champions' morning.",
  "Founders Breakfast Stout": "Coffee and double-cream chocolate stout: Michigan's official breakfast.",
  "Great Lakes Edmund Fitzgerald": "Named after the freighter that sank in Lake Erie: the sailors' porter.",
  "Löwenbräu": "The Munich lion again, bare: at Oktoberfest the lion roars in liters.",
  "Hacker-Pschorr": "The 'people's friend': the Munich revolutions' brewery.",
  "Spaten": "The brewery's 'spade': the first to advertise, back in 1894.",
  "Harvey's Tom Paine": "Named after Lewes' revolutionary: the beer of human rights.",
  "Hoegaarden Grand Cru": "The wit boosted with coriander and curaçao: wheat's grand reserve.",
  "St Bernardus Tripel": "Watou phoenix's tripel: round, spiced, silk foam.",
  "Weihenstephaner Pils": "The Bavarian monks' pils: Cistercian order meets Hallertau hops.",
  "Orval Grande Réserve": "Orval laid down: numbered bottles vanish in a blink.",
  "Cantillon Vigneronne": "Muscat grapes on lambic: the brewery bows to wine, quietly.",
  "Grimbergen Rouge": "The phoenix turns red: red fruit and caramel notes.",
  "Samuel Smith Nut Brown Ale": "Yorkshire's nutty brown: as soft as a pub by the fire.",
};
